### ISSUE TITLE
Remove user association from guest author when user is deleted / removed

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/Co-Authors-Plus#120]
When a user is deleted or removed from a site, any guest author associations they have should be deleted.

**Comment by rebeccahum** [comment]
Yes, because if they are not deleted, their byline remains beside the new "assigned" co-author (as per issue #120).

**Comment by rebeccahum** [comment]
Yes, because if they are not deleted, their byline remains beside the new "assigned" co-author (as per issue #120).
