### ISSUE TITLE
website vs url in coauthors_links_single function

### ISSUE THREAD

**Issue by frankar** [Automattic/Co-Authors-Plus#132]
In template_tags.php, function coauthors_links_single
for co-authors works if I substitute get_the_author_meta('url') with
get_the_author_meta('website') on lines 327 and 329

If my author is a normal user is right get_the_author_meta('url')

**Comment by philipjohn** [comment]
Can you elaborate on what's broken here please? Are you saying that `get_the_author_meta('url')` gives an unexpected result?

**Comment by rebeccahum** [comment]
Hi @frankar, just following up if you are able to confirm what exactly the issue you are experiencing is?

**Comment by trepmal** [comment]
1. Assign standard WP user to post
1a. Make sure WP user has Website field set in profile
2. Assign guest author to post
2a. Make sure guest author has Website set in guest author profile
3. Use `coauthors_links()`

With `get_the_author_meta('url')` only WP User will be linked. With `get_the_author_meta('website')` only guest author will be linked.
