### ISSUE TITLE
Jetpack's Google Plus Profile Overrides Guest-Author Names

### ISSUE THREAD

**Issue by alpha1** [Automattic/Co-Authors-Plus#153]
the troublemaker is located here:
/plugins/Jetpack/modules: Line 29
add_filter( 'the_author', array( $this, 'overwrite_the_author' ) );

This will rewrite every authors display name to that of the WP user. It should be filtered to disallow this. 

You can disable authorship completely by adding this line:
remove_action('init', 'jetpack_init_gplus_authorship');

but Obviously, that's not the best solution.

**Comment by rebeccahum** [comment]
Closing because Google+ is retired: https://www.blog.google/technology/safety-security/expediting-changes-google-plus/.
