### ISSUE TITLE
"Featured Image" isn't used for guest author when assigning a guest author to a post

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/Co-Authors-Plus#172]
When assigning a guest author to a post, the "Featured Image" isn't used. This is because the JS layer generates the image preview hash for the gravatar, and we aren't able to filter it.

We'll need to set up some filtering mechanism so we can slot in the featured image.

**Comment by nielslange** [comment]
Closing this issue as the "featured image" of the guest author appears on the post editor in the meantime.

<table>
<tr>
<td>Guest author screen
<br><br>

![#172-guest-author-screen](https://user-images.githubusercontent.com/3323310/113557410-2b0c0b80-9628-11eb-83b6-efdeb4b001ef.png)
</td>
<td>Post editor
<br><br>

![#172-editor](https://user-images.githubusercontent.com/3323310/113557405-28a9b180-9628-11eb-8d9b-31184aaa0a28.png)
</td>
</tr>
</table>
