### ISSUE TITLE
Guest authors with non-ASCII characters can't be used as co-authors

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/Co-Authors-Plus#198]
[Reported in the forums](http://wordpress.org/support/topic/non-ascii-guest-author-names-cannot-be-added-to-post)

Needs a fix with unit test coverage both ways so we don't accidentally break something.

**Comment by dartiss** [comment]
Now reported by a VIP client (#64148-z).

**Comment by philipjohn** [comment]
Fixed by #473
