### ISSUE TITLE
Cannot edit guest authors when 38,000+ are present

### ISSUE THREAD

**Issue by Lexicality** [Automattic/Co-Authors-Plus#206]
On a large WP install with 38,613 users, each of which have at least one guest author the "Edit Profile" link causes a page timeout. In addition various other parts of the WP-Admin stop responding during the timeout.
![2014-06-24_09-26-52](https://cloud.githubusercontent.com/assets/847422/3368779/79c9a1ca-fb79-11e3-88a6-875c7d51f475.png)

**Comment by maxfenton** [comment]
+1

**Comment by maxfenton** [comment]
@Lexicality Can you post a longer text snippet with exactly where to add that delay?

**Comment by Lexicality** [comment]
@maxfenton voilà: #316
