### ISSUE TITLE
What about a new release version?

### ISSUE THREAD

**Issue by larruda** [Automattic/Co-Authors-Plus#207]
The last 3.1.1 version is from March 20th.
Since then we had the following contributions: https://github.com/Automattic/Co-Authors-Plus/compare/3.1.1...master

What about releasing a new version then?

Please share your thoughts!

Tks.

**Comment by maxfenton** [comment]
+1

**Comment by mattoperry** [comment]
Thx!  We _finally_ released 3.1.2 two weeks ago, and a new (more substantive) release is on the way.
