### ISSUE TITLE
get_coauthor_by() with ID returning empty objects

### ISSUE THREAD

**Issue by dlh01** [Automattic/Co-Authors-Plus#212]
On a new WordPress install, if I run `$coauthors_plus->get_coauthor_by( 'id', 1 )`, I would expect to get the coauthor object for my site admin. Instead, I get an empty guest author object.

If I disable guest authors, then I get the coauthor object.

If I'm reading it correctly, this occurs when `get_coauthor_by()` calls `get_guest_author_by()` using my original arguments. I intend to check a user ID, but `get_guest_author_by()` treats it as a post ID. `get_guest_author_by()` also constructs an object out of whatever post ID it finds, regardless of type or status.

Have I misunderstood the purpose of `get_coauthor_by()` or what it's doing?

**Comment by jjeaton** [comment]
I've also just run into this issue, I think it's a bug. When querying by ID, the query should also check that it's in the 'guest-authors' post type. Similar the next query below it where it queries post_name.
