### ISSUE TITLE
Danish translation

### ISSUE THREAD

**Issue by AlexNoerregaard** [Automattic/Co-Authors-Plus#217]
Hi,

I'm new here but use Co-Authors Plus for a Danish website, so I was thinking about making a translation? How do I do that and how to down- and upload the necessary files?

Best regards,
Alex

**Comment by philipjohn** [comment]
Thanks for volunteering to contribute @AlexNoerregaard !

Please see [this guidance](http://wordpress.stackexchange.com/questions/57219/how-to-translate-a-plugin-via-po-mo) and shout if you need anything more. Once you're ready with a translation, open a Pull Request with the new translation.
