### ISSUE TITLE
Replace wp_die errors with WordPress UI error messages.

### ISSUE THREAD

**Issue by ryanmarkel** [Automattic/Co-Authors-Plus#227]
Most error messages in CAP are presented through stark wp_die screens and often those error messages can be somewhat cryptic. When possible, CAP should display error messages in the standard UI style, providing non-vague explanations as to why something can't be done.

**Comment by GaryJones** [comment]
Since this is a very general Issue, lacking specific examples, and it's getting on for nine years old, I will close it out. New issues that reference specific examples, and how to reproduce those error messages, would be accepted.

**Comment by EarthlingDavey** [comment]
Here in 2024 👋  see you in another 10 years
