### ISSUE TITLE
Recent changes to bylines/author assignments don't get reflected properly in post counts in admin UI

### ISSUE THREAD

**Issue by ryanmarkel** [Automattic/Co-Authors-Plus#228]
Whenever changes are made to authors or user account links are created, counts get messed up and can cause users to panic. :)

You can reproduce this somewhat easily:
1. Have a user account (no guest author/byline) that has authored posts. You'll see a count in the Users panel.
2. Create a new byline for that user.
3. Link that byline to that user account.
4. The counts for both the byline and the user account for number of posts will read zero.

It's not immediately clear how to adjust or fix this. Updating terms using the CLI tool has no effect.

**Comment by rebeccahum** [comment]
Re-opening because reverted #438 per https://github.com/Automattic/Co-Authors-Plus/commit/a645d596357c0b1c84c57a5a5ab9925f669050ee so this issue still exists.
