### ISSUE TITLE
Co-Authors Plus Theme: Contango Template Tags

### ISSUE THREAD

**Issue by natiop** [Automattic/Co-Authors-Plus#230]
Hi!
I really need help with changing the bylines and adding template tags that will show the multiple author bylines.
More information here: https://wordpress.org/support/topic/plug-in-co-authors-plus-theme-contango-getting-multiple-authors-to-show-up

Thanks!
Natalia

**Comment by philipjohn** [comment]
Hi @natiop, do you still have this problem, or did you find the answer?

**Comment by rebeccahum** [comment]
Hi @natiop, we haven't heard back from you in awhile, so I will close this issue! Feel free to re-open the issue if you are still experiencing problems.
