### ISSUE TITLE
Plugin issues in WP 4.0

### ISSUE THREAD

**Issue by manoj382** [Automattic/Co-Authors-Plus#233]
This plugin hasn't been updated in several months and the release notes show that it hasn't been tested in 4.0. I'm having some issues with the plugin in a 4.0 environment. Is it broken for the latest version of WP? 

There are also several open issues, but this plugin is still being suggested by WP VIP.....

**Comment by nickdaugherty** [comment]
Can you please open a separate issue detailing the problems you're having?

WordPress.com VIP is running this plugin on the latest trunk version of WP without issue.
