### ISSUE TITLE
Cannot assign co-authors with Hebrew slug + how to filter the_author_meta

### ISSUE THREAD

**Issue by ituk** [Automattic/Co-Authors-Plus#250]
Hey,
 I'm trying to use this wonderful plugin and got stuck so I have 2 issues/questions. tried to get answers on the plugin page at wordpress.org but it seems very quiet there.
1.
On the post edit screen, when I type in the co-author name I can see it and assign it to the post, but after saving the post the co-author disappears and only the wp author is assigned. I figured out that the problem accrues only when the co-author slug is in Hebrew.
So although I can manually create new co-authors in English first, and change the display name after saving, this cannot be the solution for my customer.

2.
I'm using Sahifa theme, there I have an author box at the end of a post. I'm trying to filter 'the_author_meta' and 'get_the_author_meta' with the 'coauthor' equivalents but with no success.

this is what I have:

<pre>
function guest_get_the_coauthor_meta() {
    if(function_exists('the_coauthor_meta')){
        return get_the_coauthor_meta();
    }
    else{
        return get_the_author_meta();
    }
}
add_filter( 'get_the_author_meta', 'guest_get_the_coauthor_meta' );

function guest_the_coauthor_meta() {
    if(function_exists('the_coauthor_meta')){
        return the_coauthor_meta();
    }
    else{
        return the_author_meta();
    }
}
add_filter( 'the_author_meta', 'guest_the_coauthor_meta' );
</pre>

I've also tried using get_coauthors() in some ways, but nothing.

I'd appreciate your help,
Thank you,
Itamar

**Comment by tcrsavage** [comment]
Hello all,

Doesn't look like the foreign lang characters issue has seen much traction. I came across the same issue today and produced a patch on a fork of v3.1.1.

Are we interested in merging this fix into master?

https://github.com/humanmade/Co-Authors-Plus/pull/1
