### ISSUE TITLE
Use of get_coauthor_by with user_nicename fails retrieval

### ISSUE THREAD

**Issue by joshlevinson** [Automattic/Co-Authors-Plus#277]
I was attempting to use the `get_coauthor_by` method to get a guest coauthor by their "nicename". 
However, the [switch case responsible](https://github.com/Automattic/Co-Authors-Plus/blob/3756d1bd04b4e1c6c26c42c96267d90ddeb1cb08/php/class-coauthors-guest-authors.php#L842) for searching for guest coauthors based on nicename (and post_name) runs the key through the `get_post_meta_key`, prefixing it with `cap-`. This results in SQL like:
`SELECT ID FROM $wpdb->posts WHERE post_name=cap-{$query} AND...`
I don't see a need for the key to be run through the `get_post_meta_key` method. Am I mistaken?

**Comment by philipjohn** [comment]
The code should probably not add the prefix first, and rely on `get_post_meta_key()` to do it instead. That way, if the prefix needs to change for whatever reason, it can.

**Comment by rebeccahum** [comment]
Looks like this question has been answered above.  Closing this issue now, feel free to re-open if you have any other concerns.
