### ISSUE TITLE
coauthors_ajax_suggest runs out of memory

### ISSUE THREAD

**Issue by maxfenton** [Automattic/Co-Authors-Plus#280]
On a large site with many users and guest authors, the ajax author suggestion input box doesn't respond quickly or at all.

Tracing the call 

```
http://staging.rookiemag.com/blog/wp-admin/admin-ajax.php?_wpnonce=b636a67b47&action=coauthors_ajax_suggest&post_type=post&q=ta&existing_authors=maxfenton,amyrose
```

shows an error:

```
Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 142 bytes) in /www/hc1078/staging_deploybot/blog/wp-includes/wp-db.php on line 1717
```

**Comment by sboisvert** [comment]
Hi Max!

Does upping the amount of memory to 128MB fix this? I feel like on a large site with lots of code it could be pretty easy to hit 64MB. I don't know if we can fix this.

**Comment by mjangda** [comment]
How many users + guest authors do you have on your site?

**Comment by diggy** [comment]
@mjangda I'm running into performance issues with 8K+ users. Maybe a `coauthors_search_authors_args` filter hook could help ([here](https://github.com/Automattic/Co-Authors-Plus/blob/master/co-authors-plus.php#L1085)), which would allow for setting the `role__not_in` parameter (to exclude regular subscribers, for example)?

**Comment by diggy** [comment]
@mjangda I assume a new version will be released when #376 is resolved. Any chance you could give some love to this issue as well?

**Comment by diggy** [comment]
@maintainers @mjangda It's been a while.. any chance on this getting tackled somewhere in the near future?

**Comment by sboisvert** [comment]
@rebeccahum Do you want to take a look at this and see if we can at least add the filter?

**Comment by rebeccahum** [comment]
@sboisvert I'm on it!

Hi @diggy, thanks for your patience. I will be looking into this shortly.

**Comment by rebeccahum** [comment]
@diggy The [filter hook](https://github.com/Automattic/Co-Authors-Plus/blob/master/co-authors-plus.php#L1147)  `coauthors_edit_ignored_authors` should give you what you are looking for. 

i.e.:
```
		function filter_ignored_authors( $ignored_authors ) {
			$args = array(
				'role__in' => array( 'subscriber' ),	
				);
			$ignored_authors = get_users( $args );

			return $ignored_authors = wp_list_pluck( $ignored_authors, 'user_login' );;
		}
```

**Comment by maxfenton** [comment]
Thanks so much! (Sorry I missed @sboisvert's question awhile ago. There's a very small (hundreds) number of authors/co-authors and, uh, tons of subscribers. I'll give this filter hook a try. Thanks, @rebeccahum and @diggy!
