### ISSUE TITLE
Failing `wp_get_object_terms` filter resulting in lost co authors plus data during bulk edit

### ISSUE THREAD

**Issue by david-binda** [Automattic/Co-Authors-Plus#282]
While bulk editing posts, co authors are getting lost. I was able to track it down to [failing `wp_get_object_terms ` filter](https://github.com/Automattic/Co-Authors-Plus/blob/master/co-authors-plus.php#L894)

First of all, it looks that the `'author'` string, saved in `$taxonomy` variable is being sanitized by `%s` in `$wpdb->prepare` and get's double quoted. [The query inside the filter](https://github.com/Automattic/Co-Authors-Plus/blob/master/co-authors-plus.php#L904) is thus failing.

Further, it looks like the filter is called multiple times during the `$_REQUEST['bulk_edit']` and every time with different `$args`. Not all the times a list of slugs is being requested.

This filter needs an adjustment and return correct values in order to prevent co-authors data during the bulk edit request.

PR comming in soon.

**Comment by mattoperry** [comment]
Thanks @david-binda!  We'll merge this when it comes in.
