### ISSUE TITLE
Hardcoded 'author' taxonomy in filter_wp_get_object_terms method

### ISSUE THREAD

**Issue by david-binda** [Automattic/Co-Authors-Plus#284]
Since the plugin a uses `$coauthor_taxonomy` property to store the taxonomy name, it should be used where possible.

https://github.com/Automattic/Co-Authors-Plus/blob/master/co-authors-plus.php#L896 uses hardcoded `author` string which could and perhaps should be replaced by `$this->coauthor_taxonomy`.

**Comment by mattoperry** [comment]
Confirmed.
