### ISSUE TITLE
class-coauthors-guest-authors.php on line 152

### ISSUE THREAD

**Issue by catchmyfame** [Automattic/Co-Authors-Plus#287]
Just installed the plugin and with debugging enabled I'm getting:

`Notice: Trying to get property of non-object in /var/www/html/wp-content/plugins/Co-Authors-Plus/php/class-coauthors-guest-authors.php on line 152`

**Comment by danielbachhuber** [comment]
See #285

**Comment by catchmyfame** [comment]
Cool, thanks for the quick reply. That seems to have fixed it.

I also discovered that for users with an author role, they get the errors:

Notice: Trying to get property of non-object in /var/www/html/wp-content/plugins/Co-Authors-Plus/co-authors-plus.php on line 827 
Notice: Trying to get property of non-object in /var/www/html/wp-content/plugins/Co-Authors-Plus/co-authors-plus.php on line 837

**Comment by sboisvert** [comment]
Solved in #285
