### ISSUE TITLE
Uncaught ReferenceError: $coauthors_loading is not defined

### ISSUE THREAD

**Issue by mauteri** [Automattic/Co-Authors-Plus#296]
JavaScript error. Code is cloning #ajax-loading and assigning id #coauthors-loading, but not checking that #ajax-loading exists in the first place.

**Comment by castlehouse** [comment]
Looks like this was fixed in https://github.com/Automattic/Co-Authors-Plus/commit/08d9913392e102da6b77b3ef06acd629ed90a96a too :smile: 

Thanks for reporting though @mauteri

**Comment by mauteri** [comment]
:+1:
