### ISSUE TITLE
show multiple author by role and with avatars

### ISSUE THREAD

**Issue by Perotin** [Automattic/Co-Authors-Plus#320]
Would it be possible to show different roles separatley and all with avatars? For exaple I would like to show the Author, Designer and the Photographer of the project in separate rows with their own avatars or bio.
Thanks:)

**Comment by mattoperry** [comment]
Hey @Perotin  -- can you say more?  Where would you like to show this?

**Comment by philipjohn** [comment]
Closing, given there's no response.
