### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by sboisvert** [Automattic/Co-Authors-Plus#322]
CAP is often slow, with the sql queries in https://github.com/Automattic/Co-Authors-Plus/blob/master/co-authors-plus.php#L568
https://github.com/Automattic/Co-Authors-Plus/blob/master/co-authors-plus.php#L695
https://github.com/Automattic/Co-Authors-Plus/blob/master/co-authors-plus.php#L634

We should enable

``` php
// Use simple tax queries for CAP to improve performance
add_filter( 'coauthors_plus_should_query_post_author', '__return_false' );
```

by default
And do the backfilling of 
`$ wp co-authors-plus create-terms-for-posts`
as a one time cron fix.
We should enable the ability to disable this (with a filter). And it should run automatically when the plugin is updated and when activated.
The plugin should also be profiled and other performance enhancements added where it would make sense to.

**Comment by mjangda** [comment]
Enabling by default might be an over-optimization since this only impacts large-ish sites (may need data on what the "breaking point" is). Plus, for really large sites, the backfill command takes a long time so I'm not sure using cron is a good idea.

In #319, I suggested adding better documentation for this instead.

**Comment by sboisvert** [comment]
Doing #180 instead might be good. that one is not the only slow query. Author pages can get really slow as well.

**Comment by mattoperry** [comment]
since #180 is added to 3.2, I'll remove this issue from that milestone for now.  We should continue to look for specific slowness though, and open additional issues.

**Comment by philipjohn** [comment]
Closing in favour of specific performance issues that can be directly addressed.
