### ISSUE TITLE
Assigning authors to a post using the CLI

### ISSUE THREAD

**Issue by BrekiTomasson** [Automattic/Co-Authors-Plus#327]
Quick question. Been butting my head against the CLI and can't seem to figure this one out. Is there a quick and easy way to assign a list of specific co-authors (removing any existing co-authors) to a specific post using the CLI? I've been reading the assign-coauthors code and can't quite make it out.

**Comment by philipjohn** [comment]
The `assign-coauthors` command is intended for dealing with imports, not general author assignment. There isn't really a command to do what you want I'm afraid. It's likely you'd need to create something.
