### ISSUE TITLE
Appending ACF to an author's name in the byline

### ISSUE THREAD

**Issue by nwtech** [Automattic/Co-Authors-Plus#338]
## Not an issue, more a question:

I'm using a Genesis based theme and using the [Genesis Co-Authors plugin](https://wordpress.org/plugins/genesis-co-authors-plus/) for support on our framework.

I'm using Advanced Custom Fields to add a field to the user's profile (School/organization). I'd like to append that to the end of the author's name in a post's byline, but I can't seem to figure out the best route to go.

Any suggestions?

**Comment by nwtech** [comment]
FWIW, this is what I'm attempting to use to pull that value of the ACF:

```
$author_id = get_the_author_meta('ID');
$affiliation = get_field('school-organization', 'user_'. $author_id );
```

**Comment by philipjohn** [comment]
Have you looked for hooks at the point Co-Authors Plus prints out the byline?

**Comment by rebeccahum** [comment]
Hi @nwtech, I see you haven't responded yet.  I will close this issue in hopes that you have figured this out.  Feel free to re-open this issue anytime!
