### ISSUE TITLE
Adding coauthors via database entry

### ISSUE THREAD

**Issue by BrekiTomasson** [Automattic/Co-Authors-Plus#348]
I'm building a tool that creates pending Wordpress posts using WP-JSON and some direct database manipulation, and I'm trying to get it to work with `Co-Authors-Plus` as well.

The problem is that I have the users of the tool picking which authors should be linked to the post by picking from an alphabetically sorted list of `display_name` from the `wp_users` table, which passes the value of the `wp_users.id` into the tool.

Now, the thing that I'm having trouble figuring out is how best to go from having a list of `wp_users.id` values and the Wordpress postID to having a series of things to enter into `wp_term_relationships`. Any suggestions? Will I have to manually add 1 to `wp_term_taxonomy.count` as well or is that number somehow touched by the plugin when it realizes an author has been referenced again in `wp_term_relationships` ?

**Comment by philipjohn** [comment]
What's the reason for the direct DB queries? Is there some reason why core functions can't be used?

**Comment by rebeccahum** [comment]
Hi @BrekiTomasson, I see you haven't responded yet!  I will close this issue for now in the hopes that you have figured it out already.  Feel free to re-open the issue anytime.

**Comment by aldobsom** [comment]
The reason may be inserting bulk posts via code (functions.php). 
I have this use-case to do now and I can't figure it out. 
How to add multiple users for the same spot via` wp_insert_post()`?
