### ISSUE TITLE
trying to get property on non-bject

### ISSUE THREAD

**Issue by nicgirault** [Automattic/Co-Authors-Plus#350]
Hi!

I receive an error when I publish a post:

![untitled drawing](https://cloud.githubusercontent.com/assets/551837/14560704/95c226da-0311-11e6-8048-d991fbd7f6a0.jpg)

I use version 3.1.1 and wordpress 4

**Comment by mjangda** [comment]
Does it happen every time you save a post? Can you share an example of the author usernames that you are saving to the post?

**Comment by catchmyfame** [comment]
I get a similar error but with different line numbers when I'm editing a page:

> Notice: Trying to get property of non-object in /var/www/html/wp-content/plugins/co-authors-plus/co-authors-plus.php on line 824
> 
> Notice: Trying to get property of non-object in /var/www/html/wp-content/plugins/co-authors-plus/co-authors-plus.php on line 834

**Comment by nicgirault** [comment]
@catchmyfame are you using Google Login plugin? I am and I suspect there is an incompatibility with this plugin.

The error is coming from the fact that get_user_by('slug', my_email@gmail.com) does not return the user is the get_coauthor_by function.

**Comment by catchmyfame** [comment]
@nicgirault Actually I'm not using that plugin, and now that I checked the error I was getting appears to be gone. Not sure if it was a WP update or plugin update that got rid of it.

**Comment by nicgirault** [comment]
In my case here https://github.com/Automattic/Co-Authors-Plus/blob/1ca3ab7ccf5c09f662bea7030c6a50ba6894976d/co-authors-plus.php#L821 the author_name is not the user_nicename of the database but its email.

With the Google Login Plugin: nicolasg@theodo.fr becomes nicolasgtheodo-fr

**Comment by GaryJones** [comment]
Closing for age. There was a PR, but it had conflicts.
