### ISSUE TITLE
"Author Archives" Name Incorrect

### ISSUE THREAD

**Issue by srguglielmo** [Automattic/Co-Authors-Plus#351]
I have Co-Authors-Plus from GitHub (cloned about a week ago) running on WP 4.4. I've modified the theme to use coauthors_posts_links() and all seems to be working well except for one thing.

Consider this post here: https://i.imgur.com/2J9bBIv.png

When clicking a name from there (either guest-authors or regular author), it brings me to a page that lists all the posts by that user. It works correctly and the proper posts are displayed.

However, at the top of that page, it says `Author Archives: Stephen Robert Guglielmo` regardless of which author I click (Jane Doe, Albert Einstein, or myself).

Additionally, when multiple real users create posts on a site, the `Author Archives` line displays the name of the user **who submitted the most recent post**, regardless of the name you click.

To explain this more:
Real **UserA** makes a post with various co-authors. `Author Archives` shows **UserA**, regardless of what name is clicked (and regardless of what post it's clicked on from).

Now, real **UserB** makes a post with various co-authors. `Author Archives` now shows **UserB**, regardless of what name is clicked (and regardless of what post it's clicked on from).

It shows the name of the real user who **most recently posted an item** on the site. I expected it to display the name of the user (real or co-authors) who was clicked.

If I disable Co-Authors-Plus, the "Author Archives" works properly by showing the name of the user I clicked on.

**Comment by philipjohn** [comment]
Can you share the code that prints out `Author Archives: Stephen Robert Guglielmo` please?
