### ISSUE TITLE
Change sort order of view-guest-authors page

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/Co-Authors-Plus#371]
By default, the view-guest-authors page sorts by display name. We'd like to sort it by last, first.

If this is agreeable generally, let's make this the default. If not, add the ability to filter the sort order.

**Comment by sboisvert** [comment]
I think a filter is best in this situation.

**Comment by mattoperry** [comment]
++ to a filter.

**Comment by trepmal** [comment]
At first I was looking at a simple `orderby` filter, but since first and last name are meta, it requires a bit more to be able to sort by both fields at once...

```
$args['meta_query'] = array(
	'first_name_clause' => array(
		'key'     => 'cap-first_name',
		'compare' => 'EXISTS',
	),
	'last_name_clause' => array(
		'key'     => 'cap-last_name',
		'compare' => 'EXISTS',
	),
);
$args['orderby'] = array(
	'last_name_clause'  => 'ASC',
	'first_name_clause' => 'ASC',
);
```
Any qualms about letting the entire `$args` array be filtered?

**Comment by sboisvert** [comment]
@trepmal What are your thoughts on the potential performance implications of this?

**Comment by trepmal** [comment]
Definitely a slower query when meta is thrown in.

My _very rough and unscientific_* estimates put a single meta_query clause (i.e. just sorting by last name) at about 2-3x the execution time of the default `orderby=title` query, and the double clause (last-name-then-first-name) at 4x.
May be negligible with relatively few guest authors, but the more there are, the longer the execution times get.

\* manually computing average query times in Sequel Pro on my Mac

For the curious:
```
total guest authors: 1642

# order by title. avg time: 14.17ms
SELECT sql_no_cache SQL_CALC_FOUND_ROWS wp_posts.ID FROM wp_posts WHERE 1=1 AND wp_posts.post_type = 'guest-author' AND ((wp_posts.post_status <> 'trash' AND wp_posts.post_status <> 'auto-draft')) ORDER BY wp_posts.post_title ASC LIMIT 60, 20;

# order by first_name. avg time: 43.41ms
SELECT sql_no_cache SQL_CALC_FOUND_ROWS wp_posts.ID FROM wp_posts INNER JOIN wp_postmeta ON ( wp_posts.ID = wp_postmeta.post_id ) WHERE 1=1 AND ( wp_postmeta.meta_key = 'cap-first_name') AND wp_posts.post_type = 'guest-author' AND ((wp_posts.post_status <> 'trash' AND wp_posts.post_status <> 'auto-draft')) GROUP BY wp_posts.ID ORDER BY CAST(wp_postmeta.meta_value AS CHAR) ASC LIMIT 60, 20;

# order by last_name, first_name. avg time: 57.51ms
SELECT sql_no_cache SQL_CALC_FOUND_ROWS wp_posts.ID FROM wp_posts INNER JOIN wp_postmeta ON ( wp_posts.ID = wp_postmeta.post_id ) INNER JOIN wp_postmeta AS mt1 ON ( wp_posts.ID = mt1.post_id ) WHERE 1=1 AND ( wp_postmeta.meta_key = 'cap-first_name' AND mt1.meta_key = 'cap-last_name') AND wp_posts.post_type = 'guest-author' AND ((wp_posts.post_status <> 'trash' AND wp_posts.post_status <> 'auto-draft')) GROUP BY wp_posts.ID ORDER BY CAST(mt1.meta_value AS CHAR) ASC, CAST(wp_postmeta.meta_value AS CHAR) ASC LIMIT 60, 20;

averages taken from 10 runs
```

**Comment by sboisvert** [comment]
I think that's probably safe for most sites, It could probably grow into a problem on VIP scale sites. I think allowing the $args to be filtered is the best way to go. We'll just need to be vigilant during code review and spot any changes that make it order by meta_value since there's a good chance it won't scale on VIP.
