### ISSUE TITLE
Changes to guest author meta not immediately reflected in autocomplete dropdown

### ISSUE THREAD

**Issue by aheckler** [Automattic/Co-Authors-Plus#372]
To repro:
1. Create a new guest author with a display name, first name, and last name.
2. You will see the display name correctly shown in the guest author autocomplete dropdown:![screen shot 2016-08-12 at 9 04 11 am](https://cloud.githubusercontent.com/assets/5512652/17623002/d3990b06-606b-11e6-9f57-83d6edb56841.png)
3. Go back to the guest author and change, for example, the display name: 
   ![screen shot 2016-08-12 at 9 08 05 am](https://cloud.githubusercontent.com/assets/5512652/17623092/62c90b0a-606c-11e6-997c-de3ce1146ac1.png)
4. Refresh the page where you're looking at the autocomplete dropdown.
5. Search for the guest author.

What should happen: changes in guest author meta should be reflected in the dropdown.

What happens: they aren't. The old meta is still shown. 

![screen shot 2016-08-12 at 9 08 25 am](https://cloud.githubusercontent.com/assets/5512652/17623101/6c1b6a04-606c-11e6-91f3-d725a52e2fcd.png)

The delay seems to be longer than an hour but shorter than 24 hours. I can repro on a VIP test site, so posting here.

From VIP ticket 55563.

**Comment by aheckler** [comment]
Note: if you add the user in question as a guest author, even before the meta has "synced", it still correctly adds them to the post and will show the updated meta after the page refreshes.

**Comment by TheCrowned** [comment]
Is this still an issue? I tried reproducing with your steps above, both with memcached on and off, and could not get the issue to happen.

**Comment by nielslange** [comment]
@aheckler Can you still reproduce this problem on your end? I'm unable to see this problem on my end.

**Comment by aheckler** [comment]
> Can you still reproduce this problem on your end?

No.

**Comment by nielslange** [comment]
Good to hear, @aheckler. I'll close this issue then. 😀
