### ISSUE TITLE
preg_replace all in posts_where_filter

### ISSUE THREAD

**Issue by douglas-johnson** [Automattic/Co-Authors-Plus#375]
I am experiencing an issue with #240 

It seems that changing the limit on the preg_replace from 1 to -1 can cause unintended consequences when a logged in user views an author archive. Namely, it shows private posts to any logged in user, regardless of capabilities. 

The pattern which looks for `.post_author` in the where clause is matched twice because [WP_Query->get_posts](https://core.trac.wordpress.org/browser/tags/4.6/src/wp-includes/query.php#L3178) adds an OR for the current user's private posts.

Adding `OR (wp_2_term_taxonomy.taxonomy = 'author' AND wp_2_term_taxonomy.term_id = '799')` to the query for the current user's id means that the author archive will display private posts from the author taxonomy. 
## Example

Pattern:
`/(\b(?:wp_2_posts\.)?post_author\s*=\s*(\d+))/`

Replacement:
`($1 OR (wp_2_term_taxonomy.taxonomy = 'author' AND wp_2_term_taxonomy.term_id = '799'))`
### Non Logged in User

Subject: 
`AND (wp_2_posts.post_author = 1) AND wp_2_posts.post_type = 'post' AND (wp_2_posts.post_status = 'publish')`

Outcome:
`AND ((wp_2_posts.post_author = 1 OR (wp_2_term_taxonomy.taxonomy = 'author' AND wp_2_term_taxonomy.term_id = '799'))) AND wp_2_posts.post_type = 'post' AND (wp_2_posts.post_status = 'publish')`
### Logged in User ( Contributor )

Subject: 
`AND (wp_2_posts.post_author = 1) AND wp_2_posts.post_type = 'post' AND (wp_2_posts.post_status = 'publish' OR wp_2_posts.post_author = 180 AND wp_2_posts.post_status = 'private')`

Outcome:
`AND ((wp_2_posts.post_author = 1 OR (wp_2_term_taxonomy.taxonomy = 'author' AND wp_2_term_taxonomy.term_id = '799'))) AND wp_2_posts.post_type = 'post' AND (wp_2_posts.post_status = 'publish' OR (wp_2_posts.post_author = 180 OR (wp_2_term_taxonomy.taxonomy = 'author' AND wp_2_term_taxonomy.term_id = '799')) AND wp_2_posts.post_status = 'private')`

**Comment by trepmal** [comment]
Okay, I've been discecting this query...

I don't have a complete fix just yet, but I think I've got a half-fix (still testing).

Essentially, we could make the `preg_replace` more specific. Instead of `post_author = (\d+)` which can replace more than expected, we could have replace `post_author = (' . get_queried_object_id() . ')'`.

With this, the private posts clause would only be altered if the current user is viewing their own archive, which is fine.

The half that's not fixed is if you're a secondary author (i.e. not the author in the post_author column) you won't see your private posts in the archive.

**Comment by sboisvert** [comment]
>The half that's not fixed is if you're a secondary author (i.e. not the author in the post_author column) you won't see your private posts in the archive.

What would we need to implement this? do a preg_replace for the term query?

**Comment by trepmal** [comment]
That second half is actually fixed in 08c0315. Shame on me for not following up with a comment about that :)

**Comment by philipjohn** [comment]
I'm a little confused about how much of this issue is solved or not :) @trepmal Do the two commits above address resolve the bug here?

**Comment by trepmal** [comment]
In my testing, my PR #386 fixes the problem :)

---

For posterity, here's how I reproduced the main issue:

1. Create an user with role editor ('Editor').
2. Create a guest author ('Guest') mapped to Editor.
3. Create posts for Guest, at least one set to private.
4. View the author archive for the Guest (viewing the Editor's archive should redirect to the slug for Guest). This step you're just verifying it's not 404'ing or anything.
5. Log in as a user that does not have `read_private_posts` capability ('Author').
6. View Guest's archive (like step 4) as Author (from step 5). You should be seeing private posts (or rather you *shouldn't* but you do 😛  ).

---
Unsolved edge case (may need separate ticket):

If Author is added as a co-author to one of Guest's private posts, Author _will not_ see the private post on Guest's archive, but will on their own archive. (This is specific to Guest being a guest author)

**Comment by sboisvert** [comment]
Fixed by #386
