### ISSUE TITLE
Author search for new posts not active

### ISSUE THREAD

**Issue by jlschillinger** [Automattic/Co-Authors-Plus#380]
Hope I didn't miss an already open issue for this. I've seen this bug come up in the WP plug-in Support forums, but haven't found a solution.

**Versions I'm using:**
Wordpress 4.6.1
Co-Authors Plus 3.2.1

Since updating to WP 4.6.1, I've been unable to add co-authors.  The search field doesn't function on new posts.  It appears, but the suggested users query doesn't appear and even manually entering in a name doesn't work.

I've tested it with posts that already have co-authors, which still appear in the post meta data and in listing authors elsewhere in my theme.  For both new posts and posts that already have co-authors, the search/add feature is defunct.  

It seems #379 might be a related problem, but I'm not sure.

**Comment by trepmal** [comment]
I've been unable to replicate this behavior on my end so far. If possible, could you provide any additional details?

- do you see any errors, either javascript or in your server's error log?
- are you running any code (plugins, mu-plugins, snippets in your theme) specifically to customize your use of Co-Authors-Plus?

If not, we might need to go broader and look for potential compatibility issues with the plugins and theme you're using

**Comment by trepmal** [comment]
cross reference: https://wordpress.org/support/topic/author-search-no-response/

**Comment by jlschillinger** [comment]
@trepmal thanks for getting back to me! 

**Update**
Since, I've done some additional testing, and the plugin works on Posts, new or published, if and only if the co-author you'd like to add is also a co-author somewhere else.   In my case, I have a few posts that include one of four co-authors. When I'm now creating new posts or editing others, I can add a co-author if that co-author is also already listed as one on another posts.  Essentially, I can't query all the users on our site, just the ones that were used as co-authors prior to this problem showing up.  Does that make sense? 

**As far as your questions**... 

- no, I haven't had any errors anywhere, either now or when I first started having the problem.
- and no, no customized use of the plugin.

I only call it once in the theme, in a sidebar for posts of a specific category to list them: 
`<?php if ( function_exists( 'coauthors_posts_links' ) ) {
               coauthors_posts_links('','','',''); //get the co-authors
	       // these options are between, betweenLast, before and after
		}
		else {
		the_author_posts_link(); //if there are none, get the regular author
		}
		echo '<div class="clear-both"></div>'
		?>`

**Other plugins**
I haven't tried the old, "deactivate every plugin one by one and see if it works" method yet because I was hoping it wouldn't have to come to that! That will probably now be my next step.

**Comment by trepmal** [comment]
Thanks for the followup!
Glad you got it sorted out. This might be something that can be added to the documentation to save future users the headache :)
