### ISSUE TITLE
Consider bumping min PHP requirement to 5.4?

### ISSUE THREAD

**Issue by mjangda** [Automattic/Co-Authors-Plus#384]
Continuing discussion from https://github.com/Automattic/Co-Authors-Plus/pull/381#issuecomment-261065591

@sboisvert says: "we agreed to stop supporting 5.2 for any shared plugin and make the minimum PHP version supported 5.4."

If we move forward with this, we need to:
- [ ] Add some checks to prevent fatals when activating on < 5.4.
- [ ] Update the readme.
- [ ] Update the travis config to only test on PHP5.4+.

**Comment by philipjohn** [comment]
I'm going to put this into v3.4!

What I'd like to suggest though is that we actually bump the minimum version to 5.6. What do you think?

**Comment by nielslange** [comment]
Closing this issue as the corresponding rule set had been updated accordingly in #751.
