### ISSUE TITLE
Check if Co Author is assigned

### ISSUE THREAD

**Issue by lance1572** [Automattic/Co-Authors-Plus#397]
## This is a question

I'm trying to check if a coauthor has been assigned to a post and if not then output the normal author. I'm using underscores me and wanted to output the posted_on function if there is no coauthor. For some reason, its by passing the check when there is a coauthor assigned and going straight to the else part of the condition and outputting the posted_on function. 

I should note that when the post has a coauthor I am removing the normal author as I just want to display the coauthor for articles that have coauthors. Any advice or direction would be greatly appreciated!

`  
        
    <?php if ( function_exists( 'get_coauthors' ) ): ?>
         <?php if ( isset( $coauthor->type ) && 'guest-author' == $coauthor->type ): ?>

    <div class="author">
    <?php 
        $coauthors = get_coauthors();
        foreach ($coauthors as $coauthor): ?>
    <?php 
        $archive_link = get_author_posts_url($coauthor->ID, $coauthor->user_nicename);
        $link_title   = $coauthor->display_name;
        $description  = $coauthor->description;

    ?>
    <?php if ( has_post_thumbnail($coauthor->ID)): ?>
       <div class="author-thumb">
            <?php echo coauthors_get_avatar( $coauthor, 120 ); ?>
        </div>
    <?php else: echo '';
        endif; 
    ?>
        <div class="author-info">
            <a href="<?php echo $archive_link; ?>"><?php echo $link_title; ?></a>
            <p class="sub-title"><i><?php echo  $description;?></i></p>
        </div>
    <?php endforeach; ?>
    </div>
    <?php else:

    jemma_ev_posted_on();

    endif ;?>
    <?php endif ;?>

`

**Comment by philipjohn** [comment]
Have you seen `is_coauthor_for_post()`? Does that give you what you need?

**Comment by lance1572** [comment]
Yep! thanks!!!
