### ISSUE TITLE
No longer available for Pages under the Quick Edit link

### ISSUE THREAD

**Issue by catchmyfame** [Automattic/Co-Authors-Plus#401]
I'm testing WP 4.7.2 and discovered that when I look at the list of pages, if I click "Quick Edit" for any page, the co-authors plugin isn't there -- it's just the standard WP downdown list of authors. It works fine for posts and custom post types of type post, just not pages.

If I open a page for editing the co-authors plus author options are there and work as expected.

**Comment by philipjohn** [comment]
This is expected as the plugin currently doesn't support setting co-authors from the Quick Edit panel. Open to Feature/Pull Requests though!

**Comment by philipjohn** [comment]
Oh, ha - completely didn't see the PR!

**Comment by catchmyfame** [comment]
@philipjohn But it did in recent versions, so I'd call that a bug no?

**Comment by philipjohn** [comment]
Not that I'm aware of. If you see it in a previous version, please do provide details. Otherwise, see #422 which adds Quick Edit support.

**Comment by catchmyfame** [comment]
@philipjohn  Oh, it totally did used to exist. Then back around the beginning of March (maybe earlier) I believe an update to WP caused it to no longer be on the Quick Edit page. I was just posting a bug report about it, not asking for a new feature.
