### ISSUE TITLE
(CLI) `create-terms-for-posts` fails if a post doesn't have any author terms

### ISSUE THREAD

**Issue by trepmal** [Automattic/Co-Authors-Plus#410]
If you run the WP-CLI command `wp co-authors-plus create-terms-for-posts` it'll fail once it runs into an author-less post.

In https://github.com/automattic/Co-Authors-Plus/blob/master/php/class-wp-cli.php#L52, there's this:

```
$terms = cap_get_coauthor_terms_for_post( $single_post->ID );
if ( empty( $terms ) ) {
	WP_CLI::error( sprintf( 'No co-authors found for post #%d.', $single_post->ID ) );
}
```
`cap_get_coauthor_terms_for_post()` will return an empty array for either 1) no author terms for post or 2) WP_Error

So when there are no terms, the CLI returns an error, which exits and kills the script. Not sure if the intent of the `error()` was to serve as a notice and continue.

I see three possible fixes

1. Use `wp_get_post_terms()` instead of the `cap_get_coauthor_terms_for_post()` wrapper, for better or worse, this skips caching. e.g.  

  ```
	$terms = wp_get_post_terms( $single_post->ID, $coauthors_plus->coauthor_taxonomy );
	if ( is_wp_error( $terms ) ) {
		WP_CLI::error( $terms->get_error_message() );
	}
  ``` 
2. Change `error()` to `line()` so it's non-blocking
3. Add an option in `cap_get_coauthor_terms_for_post()` to return the WP_Error instead of an empty array

**Comment by mjangda** [comment]
> Change error() to line() so it's non-blocking

Or `WP_CLI::warning`

**Comment by trepmal** [comment]
I'm not sure `warning` is appropriate in context, at least not in the case of `$terms` simply being empty. But possibly in combination with checking `is_wp_error()`.

**Comment by david-binda** [comment]
Neither the `line()` nor `warning()` is an appropriate fix without other changes, as the the command would then simply do nothing, as it would read following:

```
if ( empty( $terms ) ) {
    WP_CLI::line( ... );
}
if ( ! empty( $terms ) ) {
WP_CLI::line( ... );
    continue;
}
```

Thus I would propose using the `wp_get_post_terms()` and `is_wp_error` check as it used to be in place before the https://github.com/Automattic/Co-Authors-Plus/commit/4aea6b153941b34da5e9eb848283ffb0885288d2 . Or allowing the `cap_get_coauthor_terms_for_post ` returning WP_Error, in case it's appropriate.

The `WP_CLI::error` seems to make sense in case the `wp_get_post_terms()` returns `WP_Error`, as it means something is not quite right and needs further investigation.

**Comment by david-binda** [comment]
Please, ignore my previous comment about command not doing anything - I confused myself while thinking about the issue.

The original check was in place just for the `is_wp_error` case, and that's how I think it should stay in there.

The `empty` case is actually what the command is looking for, and thus it should not be throwing a Warning if it finds a post it wants to process. Line might be fine, but just for the sake of more posterity - which does not seem necessary.

**Comment by trepmal** [comment]
@david-binda I think I might be confusing myself by overthinking the issue :)

`line()` is the current in-progress fix, and is the simplest. With this (and as it is currently), there's no concern about a WP_Error further up. I feel like we might not really care if there was an WP_Error in `cap_get_coauthor_terms_for_post` that we ignored, but maybe there's a case I'm missing?

**Comment by danielbachhuber** [comment]
The original logic was correct:

```
$terms = get_the_terms( $single_post->ID, $coauthors_plus->coauthor_taxonomy );
if ( is_wp_error( $terms ) ) {
	WP_CLI::error( $terms->get_error_message() );
}
```

`get_the_terms()` can return a WP_Error if the taxonomy isn't registered.

The current logic is incorrect. No terms being returned is expected, because you want to generate terms for the post.

**Comment by rebeccahum** [comment]
The original logic was:
```
$terms = cap_get_coauthor_terms_for_post( $single_post->ID );
if ( empty( $terms ) ) {
	WP_CLI::error( sprintf( 'No co-authors found for post #%d.', $single_post->ID ) );
}
```

This was fix 1 that was proposed:

```
$terms = get_the_terms( $single_post->ID, $coauthors_plus->coauthor_taxonomy );
if ( is_wp_error( $terms ) ) {
	WP_CLI::error( $terms->get_error_message() );
}
```

@danielbachhuber Did you mean that fix 1 would be a better solution?

**Comment by rebeccahum** [comment]
The original logic was:
```
$terms = cap_get_coauthor_terms_for_post( $single_post->ID );
if ( empty( $terms ) ) {
	WP_CLI::error( sprintf( 'No co-authors found for post #%d.', $single_post->ID ) );
}
```

This was fix 1 that was proposed:

```
$terms = get_the_terms( $single_post->ID, $coauthors_plus->coauthor_taxonomy );
if ( is_wp_error( $terms ) ) {
	WP_CLI::error( $terms->get_error_message() );
}
```

@danielbachhuber Did you mean that fix 1 would be a better solution?

**Comment by timburden** [comment]
Hey guys, I need to run this tool so I can fix https://github.com/Automattic/Co-Authors-Plus/issues/454 . But it errors out:
``` bash
tburden@SJM-STAGING:/var/www/oursite.com/tburden.oursite.com/public_html$ wp co-authors-plus create-terms-for-posts
Now inspecting or updating 21165 total posts.
1/21165) Skipping - Post #392779 'The Ultimate Toronto Fall Tasting Box' already has these terms: staff
Error: No co-authors found for post #478.
```
The fix appears to be in source but is not in the latest release. Any idea when that will be?

**Comment by philipjohn** [comment]
Shouldn't be far away now. You could patch your existing version for the moment, if you're confident enough doing that.
