### ISSUE TITLE
posts_join_filter adding duplicate LEFT JOINS causing very slow is_author queries

### ISSUE THREAD

**Issue by kevinlisota** [Automattic/Co-Authors-Plus#417]
@trepmal @mjangda This issue appears to have been introduced in this commit: https://github.com/Automattic/Co-Authors-Plus/commit/e1bda7689236ad86c7f911ddc339f59dcb19bb6a

Enable Coauthors Plus and view the main query on an author archive page to see the resulting SQL statement.

```SELECT SQL_CALC_FOUND_ROWS wp_posts.ID
FROM wp_posts 
LEFT JOIN wp_term_relationships
ON (wp_posts.ID = wp_term_relationships.object_id)
LEFT JOIN wp_term_relationships AS tr1
ON (wp_posts.ID = tr1.object_id)
LEFT JOIN wp_term_taxonomy
ON ( tr1.term_taxonomy_id = wp_term_taxonomy.term_taxonomy_id )
WHERE 1=1 
AND ((wp_posts.post_author = 83872
OR (wp_term_taxonomy.taxonomy = 'author'
AND wp_term_taxonomy.term_id = '12475')))
AND wp_posts.post_type IN ('post', 'sponsor_post')
AND (wp_posts.post_status = 'publish'
OR wp_posts.post_status = 'private')
GROUP BY wp_posts.ID
HAVING MAX( IF ( wp_term_taxonomy.taxonomy = 'author', IF ( wp_term_taxonomy.term_id = '12475',2,1 ),0 ) ) <> 1 
ORDER BY wp_posts.post_date DESC
LIMIT 0, 30
```
Notice that the wp_term_relationships LEFT JOIN with wp_posts is repeated twice. Once with an alias and once without an alias. This duplicate join statement does not cause the SQL query to fail, but it does make the query extremely slow. Without the duplicate join, my is_author main query takes 0.1s. When the duplicate join is there, the same query takes 1.0-1.5 secs to return a result.

I'm not entirely sure why the aliased query was needed, but the fix might be as simple as reverting that commit.

If for some reason the aliased query needs to be there, the code needs to replace the unaliased query, not add to it, which is what it does now.

**Comment by sboisvert** [comment]
Thanks for the report Kevin!

Can you confirm that the fix we put in get's the performance back where it was before?

**Comment by trepmal** [comment]
Forgot to share some results of my own... These numbers are coming from a local test site with about 1k posts. I ran the before/after SQL 10 times each (with `SQL_NO_CACHE` set), and took the average. Before: 11.39ms; After: 6.45ms

Additional confirmation from Kevin would be grand :)

**Comment by kevinlisota** [comment]
Will have a report for you shortly once I roll in that change this evening. We have 30k posts and lots of terms, so will be a more robust test.

**Comment by kevinlisota** [comment]
This greatly improves query performance on our system. Before the fix, the is_author main query took 1.2-1.4sec. After removing the redundant JOIN, the main query now takes ~0.2 sec. 

Still not a fast query, but definitely a worthwhile fix that brings it inline with where it was before.

**Comment by nicholasio** [comment]
This took down one of our client sites that has a huge traffic after we updated to 3.2.2, we had to rollback to get site back up. I think it's worth considering making this a minor urgent update.

**Comment by trepmal** [comment]
@nicholasio would you happen to have the error handy? Feel free to open a new issue with any additional specifics, thanks.
