### ISSUE TITLE
0 posts for Guest Author different than 0 posts for WP User

### ISSUE THREAD

**Issue by trepmal** [Automattic/Co-Authors-Plus#425]
Related #201, #409

**Setup**

I have created 2 users:
 * `lazy-author`: A standard WP User (role: author) with 0 posts
 * `lazy-guest`: A Guest Author with 0 posts

Author archive for the first - http://local.wordpress.local/author/lazy-author/ - returns a 200, with "no posts found"

Author archive for the second - http://local.wordpress.local/author/lazy-guest/ - returns a 404, with an "oops" message

I'm not sure we should return a 404, as this doesn't match core behavior. I think we might just be dealing with cruft left over after copy-pasta rotted a bit.

**Comment by rebeccahum** [comment]
+1 to this for consistency with core.  It would also cause less confusion for those building custom author templates with this plugin.

**Comment by philipjohn** [comment]
Agreed, let's make this consistent with core.
