### ISSUE TITLE
create-guest-authors should show some sense of progress

### ISSUE THREAD

**Issue by trepmal** [Automattic/Co-Authors-Plus#429]
The `create-guest-authors` CLI command is silent till the end. I'm running it on a site now, and I get the feeling it's going to be a while, but I have know idea if it'll actually be 5 minutes or 5 hours.

It should show either a progress bar or line-by-line success/failure output (even if with a `--verbose` flag) to give the user some indication of finish time.

**Comment by trepmal** [comment]
(By the way, the site had 2500+ users, and it took over 6 hours for the command to complete)

**Comment by sboisvert** [comment]
Fixed in #431
