### ISSUE TITLE
posts_join_filter()  -- Massive load

### ISSUE THREAD

**Issue by andyphillips82** [Automattic/Co-Authors-Plus#445]
Our databases are having massive issue with this filter.  Author pages are taking 30 to 60 seconds to respond.

Any idea why?

**Comment by rebeccahum** [comment]
@andyphillips82, have you tried adding the filter:
`add_filter( 'coauthors_plus_should_query_post_author', '__return_false', 10, 2 )`

Note: before you add the filter, it is recommended to run the WP CLI command `create-terms-for-posts`.

**Comment by rebeccahum** [comment]
@andyphillips82, have you tried adding the filter:
`add_filter( 'coauthors_plus_should_query_post_author', '__return_false', 10, 2 )`

Note: before you add the filter, it is recommended to run the WP CLI command `create-terms-for-posts`.

**Comment by rebeccahum** [comment]
@andyphillips82, have you tried adding the filter:
`add_filter( 'coauthors_plus_should_query_post_author', '__return_false', 10, 2 )`

Note: before you add the filter, it is recommended to run the WP CLI command `create-terms-for-posts`.

**Comment by andyphillips82** [comment]
That looks like it worked!   thanks so much!
