### ISSUE TITLE
CAP's filtering of count_user_posts has side-effects on REST API usage

### ISSUE THREAD

**Issue by jacklenox** [Automattic/Co-Authors-Plus#447]
At the moment, the core REST API uses `count_user_posts` in its permissions checks to see if a request has access to read a user. See the line in question [here](https://core.trac.wordpress.org/browser/tags/4.8.1/src/wp-includes/rest-api/endpoints/class-wp-rest-users-controller.php#L379).

CAP's filtering of `count_user_posts`, [as seen here](https://github.com/Automattic/Co-Authors-Plus/blob/c066be2/co-authors-plus.php#L943-L958), has side-effects on the REST API's functionality when it changes this count from the API's core expectation.

We should seek to make CAP REST API aware so that it functions as expected when used in combination with the REST API.

**Comment by rebeccahum** [comment]
Closing because we've removed `wpcom-helper.php`.
