### ISSUE TITLE
New pages don't show up in list of "parent" pages

### ISSUE THREAD

**Issue by catchmyfame** [Automattic/Co-Authors-Plus#451]
I created a few new pages and when I went to change the "parent" of one page to point to one of the other new pages I created, none of the new pages I created were listed. When I deactivated CAP all my new pages showed up right away in the list of parents. Fortunately when I reactivated CAP it still showed up in the list, however this means that CAP is doing something to stop new pages from being added to the list when created.

**Comment by rebeccahum** [comment]
Hi @catchmyfame, where exactly are you seeing the pages disappear from?  Which list are you referring to?  If you can provide some more detailed steps on how to reproduce, that would be awesome.  Thanks!

**Comment by catchmyfame** [comment]
Hi @rebeccahum, I'm referring to when editing a page, under the Page Attributes box there's a Parent drop down list. When CAP is enabled, the new pages I create don't show up there. If I disable CAP, edit any new pages or create new pages, they then show up in that list.

**Comment by rebeccahum** [comment]
Hmm. I don't seem to be experiencing this issue on my end.

**Comment by catchmyfame** [comment]
I'm pretty sure this can be closed. I'm not sure if it was the new version of CAP and/or a WP update, but I can't reproduce this anymore.
