### ISSUE TITLE
Filtering the get_avatar hook does not change avatars in author selection widget

### ISSUE THREAD

**Issue by fschroiff** [Automattic/Co-Authors-Plus#452]
With javascript active the author selection widget seems to only show gravatar avatars. I filter `get_avatar` to show some other image. Would be nice if that could be reflected in the author selection widget as well.

**Comment by mostafaabd** [comment]
Hello, i'm a new contributor,  so can i fix this issue, and also there is no more documentation to test my changes before send pull request for php and jquery code.

**Comment by rebeccahum** [comment]
Closed per #621.
