### ISSUE TITLE
Load issues

### ISSUE THREAD

**Issue by timburden** [Automattic/Co-Authors-Plus#454]
We have had to roll back co-authors plus to version 3.2.1 on two different sites because of load issues, seems to be related to new db queries that only affect the authors pages.

**Comment by rebeccahum** [comment]
Hey @timburden, are you able to give us more details on this?

**Comment by rebeccahum** [comment]
Are you able to provide more details on this, @timburden?

**Comment by rebeccahum** [comment]
Hey @timburden, would you have any more details on this?

**Comment by rebeccahum** [comment]
Heya @timburden, do you have any more details on this?

**Comment by rebeccahum** [comment]
Would you happen to have more details on this, @timburden?

**Comment by timburden** [comment]
Sorry, for some reason I did not see your comment.

On two of our sites which get decent levels of traffic, we have had to lock down Co-Authors plus at v3.2.1, because after that new queries were introduced for, I believe, the authors page(s) only.

I feel like this is related to https://github.com/Automattic/Co-Authors-Plus/commit/786777a38bde89c84852794e05a844f932b7f596

Even though that commit was made over a year ago. So I don't understand why it's cropping up now, but 3.2.2 very definitely causes high DB loads, and downgrading to v3.2.1 fixes it. I am not sure if it is related to recent WP core upgrades. Our sites are currently running 4.8.1

Thank you

**Comment by philipjohn** [comment]
What are the new queries that you're seeing on author pages that weren't presented before v3.2.1? How long are those queries taking?

**Comment by philipjohn** [comment]
Actually, if you have a large database, this might be expected. Take a look at "I have a large database, will this make it slow?" in the [Readme](https://github.com/Automattic/Co-Authors-Plus/blob/master/README.md) for a possible solution.

**Comment by timburden** [comment]
Thank you very much. Adding that filter does indeed fix the load issue. However I still can't implement this solution because the WP CLI tool won't complete. See: https://github.com/Automattic/Co-Authors-Plus/issues/410
