### ISSUE TITLE
Inaccurate Linked Guest Author post count if Guest Author made post prior to Linking

### ISSUE THREAD

**Issue by rebeccahum** [Automattic/Co-Authors-Plus#460]
1. Create user account named "Editor" with user role of "Editor"
2. Create guest author account named "Guests"
3. Create post by "Guests".
4. Link user account "Editor" to "Guests".
5. Go to Users > Guest Accounts and you will see that there is an inaccurate post count.

It should count both the posts from the guest author and linked account for accuracy.

**Comment by sboisvert** [comment]
Closed in #461

**Comment by rebeccahum** [comment]
Re-opening as this has been merged over in https://github.com/Automattic/Co-Authors-Plus/commit/ecf869994b79e2e90976aa293bc3f7a861509358 so the issue still remains.

**Comment by nielslange** [comment]
**Detailed steps to reproduce:**

1. Create an editor account
2. Create two posts using the editor account
3. Create a guest author account
4. Create one post using the guest author account
5. Link the guest author account to the editor account

**Expected behaviour**

- Editor post count: 3 → ✅
- Guest author post count: 3 → ✅

**Current behaviour**

- Editor post count: 3 → ✅
- Guest author post count: 5 → ❌

**Comment by htdat** [comment]
I am not sure if this makes sense but here what I could find out so far. 

Start at these lines in getting post counts for co-authors:

https://github.com/Automattic/Co-Authors-Plus/blob/c9ebbd1e02741743e109e8c3f45cc38d62d25e4d/php/class-coauthors-wp-list-table.php#L271-L284

As I understand, the `if` logic here means if this is a linked account, it will make the sum of two parts:

*   number of posts from the co-author. (1)
*   number of posts from the linked author (real user in WP system). (2)

But part (1) actually has already covered part (2) in this case as we can see in the method `CoAuthors_Plus::get_guest_author_post_count` [(code ref)](https://github.com/Automattic/Co-Authors-Plus/blob/c9ebbd1e02741743e109e8c3f45cc38d62d25e4d/co-authors-plus.php#L1729-L1729
).

*   It checks if this user is a linked account, then it will return `count_user_posts( $user->ID )`;
*   This function `count_user_posts` actually applies this filter `get_usernumposts`. ([code ref](https://href.li/?https://github.com/WordPress/WordPress/blob/133c4e2e509845e29ab7b25671bea2cc7cbf7f52/wp-includes/user.php#L569))
*   And CAP has a filter function for it `CoAuthors_Plus::filter_count_user_posts` ([code ref](https://href.li/?https://github.com/Automattic/Co-Authors-Plus/blob/c9ebbd1e02741743e109e8c3f45cc38d62d25e4d/co-authors-plus.php#L1050-L1050)).

IMHO, a simple fix… is to remove the `if` logic in the code I mentioned above. More specifically, they’re L275-L282.

Well, even so, @nielslange and I think we may carefully check for all usages of mentioned functions above and add some tests here.

**Comment by nielslange** [comment]
Thanks for the additional notes, @htdat. I'll be working on test cases today, so that we can see if a potential fix works as expected for all cases.
