### ISSUE TITLE
Problem creating guest author page when multiple guest authors are present in last post

### ISSUE THREAD

**Issue by xpander001** [Automattic/Co-Authors-Plus#462]
I am trying to create a coauthor page, like `myblogdomain/author/jkrowling`.

However I'm finding an issue when that guest author's last post is shared with other guest authors.

Seems that when loading the author's page, the last post by that author is loaded. However, if that last post is shared with other authors, I'm not sure what is the proper way to select the author that corresponds to the author url.

An example:

jkrowling's last post is written by jrrtolkien and jkrowling (in that order). If I access to `/author/jkrowling`, and do:

```
global $post;
var_dump( $post);
```

I see the last post written by both, but I have no clue about the proper way to know that jkrowling is the author searched in the url and retrieve only that author data. Cannot find also if there are template tags to be used in the author page instead of the post loop.

PD: I know that this is not probably a bug itself, but could not think about a better place to include the question :)

**Comment by xpander001** [comment]
Update:

I'm retrieving it using `<?php $coauthor = get_queried_object(); ?>` , but I'm not sure if it's the proper way,

**Comment by Ekatchi** [comment]
So what you're looking for is to search for a specific author, if I'm understanding? I believe that the search_authors function is what you're looking for, but I might have misunderstood what you're trying to do.

**Comment by GaryJones** [comment]
Getting the queried object is a great way of finding out who the main query was meant to be about.
