### ISSUE TITLE
Allow Multiple Authors to show in search?

### ISSUE THREAD

**Issue by KrashKartMedia** [Automattic/Co-Authors-Plus#463]
I have this post "https://www.psehealthyenergy.org/our-work/publications/archive/clean-energy-pathway-for-nj/" and multiple authors. When I search for ELENA KRIEGER, the post comes up. When I search for BORIS LUKANOV, nothing comes up.

When I change the order of the authors around, then the post shows under Boris's name.

Any way I can make the WP search, look for both authors, and not just one?

**Comment by Ekatchi** [comment]
Isn't this just happening because of how co-authors are included in a page, not actually being considered an "author" but are instead just considered "co-authors"?

**Comment by KrashKartMedia** [comment]
Right. Is there a hook I could use to add the data to search?

**Comment by caralbgm** [comment]
Hi @KrashKartMedia , was you able to sort this out? I also need to allow search by authors in a site and we are using this plugin, so I want to know if you already achieve this and also if you can share with us. Thanks!

**Comment by tw2113** [comment]
@caralbgm I'm one of @KrashKartMedia's coworkers. We never found a solution for this yet.

**Comment by TheCrowned** [comment]
Hi @KrashKartMedia and @tw2113 - I was having a look at this issue, but I am not able to reproduce it. Apparently, the WP default search function doesn't allow to search for author. If you search for "Charlie Chaplin", you will only get posts that contain those words, no authored by a user with that name (provided it exists, of course!). So how are you doing it? Are you using a plugin to boost the search function? Custom code?

**Comment by tw2113** [comment]
I believe we ended up coupling up CoAuthor with the "Search Everything" plugin and got the type of results we were looking for.
