### ISSUE TITLE
Where is the information about co-authors stored in the wordpress database?

### ISSUE THREAD

**Issue by mayureshmandan** [Automattic/Co-Authors-Plus#466]
Like the author ID is stored in the wp_posts table under the post_author column which references the ID in the wp_users table. And additional info is in wp_usermeta table.

**Comment by rebeccahum** [comment]
Hi @mayureshmandan, if I am understanding your question correctly, you can find co-author information (e.g. first name and last name) in `wp_postmeta`.

**Comment by MastaBaba** [comment]
What is the key they are stored under?
