### ISSUE TITLE
Add rich text to guest authors description

### ISSUE THREAD

**Issue by xpander001** [Automattic/Co-Authors-Plus#479]
Is there any way to modify the plugin behaviour to replace the authors bio textarea for a rich text editor?

I have the requirement to add links and formatted text to the author's bio, but I'm not sure if this is possible/recommended. Adding a new custom field with rich text content would be also valid.

**Comment by philipjohn** [comment]
It's likely possible to do so, yes, and there are probably plugins available that add this. It's out of scope for Co-Authors Plus though.
