### ISSUE TITLE
Coauthors with non-english characters are not assigned to posts

### ISSUE THREAD

**Issue by ituk** [Automattic/Co-Authors-Plus#481]
Coauthors with non-english characters are not assigned to posts at all. I can create them, or use existing ones from the past, but cannot assign them to posts. in addition, non english display names are not encoded in the autocomplete ajax box.

Steps to reproduce:
1. use an existing or add a new coauthor with non-english unique slug. e.g איתמר-מגד
2. in post edit screen, find the coauthor and choose it.
3. delete the original author.
4. save post.
=> nothing changes.

Assigning non-english slug coauthors with 2.7-alpha1 version of the plugin works perfectly.

Thanks,
Itamar

**Comment by philipjohn** [comment]
Hiya, thanks for the detailed steps to reproduce! Could you confirm that the exact steps steps with English characters has different behaviour? I want to be sure this is a character issue and not something wider.

> Assigning non-english slug coauthors with 2.7-alpha1 version of the plugin works perfectly.

Can you confirm what this refers to please? I'm not aware of a 2.7-alpha1, and the latest verison is 3.2.2.

Thanks!

**Comment by JayWood** [comment]
Following this, ran into it on a client project today with Japanese characters. Will provide further testing at a later point. But my version is 3.2.2 currently. Will do further testing with current version but from what I can tell is the following:

When saving a guest author with non-english characters, the display-name, and subsequent post name is passed through `sanitize_title()` which handles UTF8 encoding by WordPress' core `sanitize_with_dashes()` which looks and sees if `seems_utf8()` is true or not, and if so, it will `utf8_uri_encode()` the title.

However, in the dropdown, the `$user->nicename` is coming in as the URI encoded counterpart, at least for us. Resulting in double encoding, or improper encoding when saving the post, therefore the author is never found.

While I do have a workaround currently, I want to confirm this is still an issue with the core plugin itself, without our theme-based modifications.

**Comment by JayWood** [comment]
I was able to confirm this evening that this is no longer a valid issue on either `master` or the `3.3.0` tag.

![](https://i.gyazo.com/be1dfebabb7a0e95b7230bc613579b64.gif)

**Comment by rebeccahum** [comment]
Thanks for letting us know @JayWood.  I'll close this for the time being then.
