### ISSUE TITLE
Author Archive Issues with Non-User Authors and CPT

### ISSUE THREAD

**Issue by nerdworker** [Automattic/Co-Authors-Plus#491]
I have been puzzling over this for days, so I didn't know what else to do but come to the experts.

I'm using Co-Authors Plus on a Memberpress membership site also using the Genesis Framework. This site has a normal blog and a second blog created with a CPT for members only (in case any of those things matter to this problem).

I have Co-Authors Plus functioning OK except for author archives. This is what I'm experiencing (with no custom author archive template):

- For authors who are users - I get an author archive page that only lists posts from the normal blog. Any posts from the CPT blog are not listed.
- For authors who are not users - If the non-user author ONLY has posts in the CPT blog, then the author archive link results in a 404 page. If the non-user author also has normal blog posts, you get an author archive page with only the normal blog posts and not the CPT blog posts.

So my questions would be: should my author archives be working correctly in this scenario "out of the box" or would I always need customization to make them work? If I need customization, would you please clue me in to what I should be doing, as I haven't been able to work it out. I'm fine with coding, I just need some guidance in this instance. I'm not certain if my CPT is the source of the problem, but I suspect that it is.

Any direction would be appreciated.

**Comment by rebeccahum** [comment]
Hey @nerdworker, if you are able to provide us with any steps on how to reproduce the issue, that would be the next step.

**Comment by nerdworker** [comment]
**Update:** The problem was due to the fact that the author archives only look at regular blog posts and I'm using a CPT. So I had to hook in to `pre_get_posts` to include my CPT.
