### ISSUE TITLE
Any plan on a new release?

### ISSUE THREAD

**Issue by garubi** [Automattic/Co-Authors-Plus#498]
Hallo,
since several months I'm running the plugin pulling it directly from GitHub because it has lot of fixes and improvement compared to the 3.2.2 version published on WP repository.
While I can see that there are some issues opened here, I have to say that in my usage I haven't had any problem at all.
Why not release an update from the master branch here?
At least it could fix and close lot of pending problems with the released version.

**Comment by rebeccahum** [comment]
Thanks for asking, @garubi.  We're still working on a few small fixes before we release 3.3, but we're hoping that it should be fairly soon!  cc @philipjohn

**Comment by rebeccahum** [comment]
@garubi Feel free to look through the issues and submit any PRs!
