### ISSUE TITLE
No post ID provided for CoAuthorsIterator constructor. Are you not in a loop or is $post not set?

### ISSUE THREAD

**Issue by philipjohn** [Automattic/Co-Authors-Plus#499]
Multiple tests, including new ones, are failing with this error:

> No post ID provided for CoAuthorsIterator constructor. Are you not in a loop or is $post not set?

The [build history](https://travis-ci.org/Automattic/Co-Authors-Plus/builds) suggests this broke with #474  (cc @sanketio )

**Comment by sanketio** [comment]
@philipjohn : I've fixed this and send PR #500 , Please review it and let me know if all is working fine or not.

**Comment by philipjohn** [comment]
Fixed by #500

**Comment by MastaBaba** [comment]
I just did a fresh install of 3.3, added a bunch of posts and for one post added a second author. Right then, every page, frontend and backend, started generating this notice.

**Comment by rebeccahum** [comment]
@MastaBaba Any other information you can provide for reproducing?

**Comment by MastaBaba** [comment]
Not sure what I can add; I had a clean Wordpress install, installed co-authors plus, created a few posts, added an additional author to one post. Then every page returned the notice above. 
I had debug mode turned on. I had to turn it off to be able to continue working.
