### ISSUE TITLE
Test case code doesn't make the expected change

### ISSUE THREAD

**Issue by binodkalathil** [Automattic/Co-Authors-Plus#505]
[This](https://github.com/Automattic/Co-Authors-Plus/blob/a9bbf98d3123c943f1cef67b6f7c67435a794ebd/tests/test-template-tags.php#L598) line of code doesn't make the expected change as the author(Guest Author) is stored in `posts` table.

The code updates `usermeta` table but the guest authors are stored is `posts` table and we should be updating `postmeta` table instead.

Code:
```PHP
$this->author1->type = 'guest-author';
$this->assertNull( coauthors_links_single( $this->author1 ) );
update_user_meta( $this->author1->ID, 'website', 'example.org' );//Line of code in question
$this->assertNull( coauthors_links_single( $this->author1 ) );
```

**Comment by philipjohn** [comment]
Thanks for reporting - can you point to the test this code sits within please?

**Comment by binodkalathil** [comment]
@philipjohn the test:
https://github.com/Automattic/Co-Authors-Plus/blob/a9bbf98d3123c943f1cef67b6f7c67435a794ebd/tests/test-template-tags.php#L582

The code:
https://github.com/Automattic/Co-Authors-Plus/blob/a9bbf98d3123c943f1cef67b6f7c67435a794ebd/tests/test-template-tags.php#L598

**Comment by binodkalathil** [comment]
@philipjohn, the provided info is what you needed right? Let me know if there is something else I need to add.

**Comment by TheCrowned** [comment]
Hi @binodkalathil,
I think the code is right in updating the `wp_postmeta` table, but it's actually using the wrong `meta_key`. It should be `cap-website` instead of just `website`. I will update the test accordingly :)

Have a nice day and thanks for reporting!
