### ISSUE TITLE
Empty or Incomplete Author Archives for Guest Authors with Linked Account

### ISSUE THREAD

**Issue by douglas-johnson** [Automattic/Co-Authors-Plus#510]
This may be the same as issue as #465 

After upgrading to CAP 3.3, in both my local VVV and production VIP environments, my author archives are missing all preexisting posts for any guest author with a linked account. 

I think the problem is in `posts_where_filter` and `get_author_term`

The WHERE clause comes out looking like this...

```
WHERE 1=1
AND (( (wp_2_term_taxonomy.taxonomy = 'author'
AND wp_2_term_taxonomy.term_id = '622')
OR (wp_2_term_taxonomy.taxonomy = 'author'
AND wp_2_term_taxonomy.term_id = '622')))
AND wp_2_posts.post_type = 'post'
AND (wp_2_posts.post_status = 'publish'
OR wp_2_posts.post_status = 'private')
```

This problem is the duplication of the term_id 622. That is the term ID for this Guest Author's linked account.

If I remove their linked account, the author archive starts working again.

This line in `get_author_term` will always return the linked_account if it exists.
https://github.com/Automattic/Co-Authors-Plus/blob/3.3.0/co-authors-plus.php#L1414

So when `posts_where_filter` calls `get_author_term`

here:
https://github.com/Automattic/Co-Authors-Plus/blob/3.3.0/co-authors-plus.php#L676

and here:
https://github.com/Automattic/Co-Authors-Plus/blob/3.3.0/co-authors-plus.php#L682

It returns the same value twice

**Comment by rebeccahum** [comment]
It's from this commit: https://github.com/Automattic/Co-Authors-Plus/commit/c281135c8f2054917875868a65658f325eb02177 from this PR: https://github.com/Automattic/Co-Authors-Plus/pull/461

Applicable tests: https://github.com/Automattic/Co-Authors-Plus/blob/master/tests/test-coauthors-plus.php#L539

**Comment by rebeccahum** [comment]
Thanks for reporting this @douglas-johnson.  Can you please provide the steps on how you reproduced this locally on VVV?

**Comment by philipjohn** [comment]
I'm struggling to reproduce this locally. Could you share some exact steps to reproduce please? I may be misunderstanding the effect of this issue. Here's what I tried:

1. Assigned a bunch of posts to a WP user, "Author A"
2. Checked the author archive - all posts showed
3. Checked the admin author archive - all posts showed
4. Linked a co-author called "Guest A" to the "Author A" user
5. Refresh both author archive views and saw no change.

**Comment by douglas-johnson** [comment]
@rebeccahum will do by this afternoon

**Comment by rebeccahum** [comment]
Thanks for the steps, @douglas-johnson!  I'm able to reproduce now.  

Based on your test, I'm seeing that any posts assigned to guest author `dip-dobson` disappear and only the posts assigned to WP user `dipdopson` appear in the author archive.  It should show both posts from `dip-dobson` and `dipdopson`.
