### ISSUE TITLE
Incorrect co-author search argument

### ISSUE THREAD

**Issue by SeanDS** [Automattic/Co-Authors-Plus#513]
The [`search_fields` key](https://github.com/Automattic/Co-Authors-Plus/blob/432d6b0a12d96bd97d5fcb740f8ad90a25241962/co-authors-plus.php#L1169) in the search arguments array in `CoAuthors_Plus::search_authors` should be `search_columns` as per the WordPress documentation for `WP_User_Query`. Currently the columns specified are ignored and the [WordPress defaults](https://codex.wordpress.org/Class_Reference/WP_User_Query#Search_Parameters) are used.

**Comment by rebeccahum** [comment]
Fixed by #519
