### ISSUE TITLE
v3.3.0 Breaks translation of author name and 'Author: %s' string translation for get_the_archive_title() function

### ISSUE THREAD

**Issue by jxn** [Automattic/Co-Authors-Plus#515]
It looks like this was introduced here: https://github.com/Automattic/Co-Authors-Plus/commit/8f8a0e7ca47a82e28351aa4c29556cd00177b254

After that commit, author name no longer translates.  For instance, in author.php, 
```
<?php
                    $archive_title = get_the_archive_title();
?>
```

This now returns `Author: slug-of-author-not-translated-name` in all languages.
Neither the author name (only the slug) nor the word 'Author: ' is translated.
Both should translate.

Backing out this commit fixes the issue.

**Comment by rebeccahum** [comment]
PR #516 fixes this. Resolved now.
