### ISSUE TITLE
Clicking on "No authors found" will add an empty author

### ISSUE THREAD

**Issue by TheCrowned** [Automattic/Co-Authors-Plus#525]
**Steps to reproduce:**
1. Go to a post edit page
2. In the Authors box, enter a query that will yield no results
3. Click on the message that says that no results were found
4. A blank author is added

![cap](https://user-images.githubusercontent.com/7880569/40778570-e302f4e6-64d1-11e8-9dd4-5a3e8df687b6.gif)

When saving the post, the empty author doesn't create any issue and is just ignored, but it would be nice not to have anything happen when clicking on the error.

**Comment by nielslange** [comment]
Closing this based on https://github.com/Automattic/Co-Authors-Plus/pull/527#event-2507133178.

**Comment by rebeccahum** [comment]
@nielslange Is this issue still reproducible?

**Comment by nielslange** [comment]
> @nielslange Is this issue still reproducible?

Nope, it's not. Empty authors can no longer be added.
