### ISSUE TITLE
"Trying to get property of non-object" warning in class-coauthors-wp-list-table.php

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/Co-Authors-Plus#533]
On /wp-admin/users.php?page=view-guest-authors&orderby=last_name&order=asc, I'm seeing this error.

```
Notice: Trying to get property of non-object in /srv/www/fivethirtyeight/public_html/wp-content/plugins/vip/co-authors-plus/php/class-coauthors-wp-list-table.php on line 256
```

**Comment by paulschreiber** [comment]
This happens when `$item->linked_account` is a string an not an object.

**Comment by GaryJones** [comment]
The `column_posts()` method no longer has a reference to `->linked_account` in it, so this is likely to have been handled.
