### ISSUE TITLE
the_archive_title() method returns null on non-author templates

### ISSUE THREAD

**Issue by jacobarriola** [Automattic/Co-Authors-Plus#549]
The `the_archive_title()` method when used on non author templates returns null. I suspect the issue is because there is a function that is hooked to the `get_the_archive_title` filter and fails to return the `$title` value. 

I have a [PR](https://github.com/Automattic/Co-Authors-Plus/pull/535) for this. How should we proceed with the PR?

Thanks!

**Comment by rebeccahum** [comment]
Merged #535
