### ISSUE TITLE
Inaccurate posts count for guest authors with linked accounts

### ISSUE THREAD

**Issue by TheCrowned** [Automattic/Co-Authors-Plus#556]
The posts count shown in the guest authors table is inaccurate when guest authors have linked accounts.

The issue lies in `filter_count_user_posts()`, that totally disregards che input `$count`. Thus, the posts published prior to CAP install are not considered and the count can be drastically different.

```
function filter_count_user_posts( $count, $user_id ) {
		$term = $this->get_author_term( $user );
		$guest_term = get_term_by( 'slug', 'cap-' . $user->user_nicename, $this->coauthor_taxonomy );

		...

			if ( $term && ! is_wp_error( $term )) {
				$count = $guest_term->count + $term->count;
			} else {
				$count = $guest_term->count;
			}
```

Instead of `$count = ` we should probably have `$count += `.

**Comment by rebeccahum** [comment]
What happens to the count after run of `wp co-authors-plus create-terms-for-posts`?

**Comment by TheCrowned** [comment]
The counts become correct at that point.

It would be nice to have a cron on plugin activation that would execute the same task :)

**Comment by rebeccahum** [comment]
Running `wp co-authors-plus create-terms-for-posts` will jack up the count once all the terms pre-CAP install are created.  Closing.
