### ISSUE TITLE
Migrate author terms from `$username` to `cap-$username`

### ISSUE THREAD

**Issue by TheCrowned** [Automattic/Co-Authors-Plus#566]
Since the non-prefixed `$username` term is outdated (see [`update_author_term`](https://github.com/TheCrowned/Co-Authors-Plus/blob/master/co-authors-plus.php#L1452), which, when inserting, uses the prefixed `cap-`version) I think we should migrate terms to all having the prefix. We could run a `wp_update_term()` on `update_author_term()` if needed and that should settle it.

**Comment by TheCrowned** [comment]
Quick note to say that there is already a CLI command `migrate_author_terms` to do so. Still nice to have it done on old installs on the fly as outlined above.

**Comment by GaryJones** [comment]
I think the number of old installs would now be insignificant.
