### ISSUE TITLE
CI build process uses deprecated phpcs ruleset

### ISSUE THREAD

**Issue by smistephen** [Automattic/Co-Authors-Plus#577]
Travis currently checks code against the `WordPress-VIP` ruleset:
https://github.com/Automattic/Co-Authors-Plus/blob/master/.travis.yml#L78

This ruleset is deprecated and set to be removed:
https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1309

Solution: Move to the `WordPressVIPMinimum` ruleset:
https://github.com/Automattic/VIP-Coding-Standards

**Comment by nielslange** [comment]
Closing this issue as the corresponding rule set had been updated accordingly in https://github.com/Automattic/Co-Authors-Plus/pull/751.
