### ISSUE TITLE
Mismatch between different post counting methods

### ISSUE THREAD

**Issue by TheCrowned** [Automattic/Co-Authors-Plus#583]
When [registering a taxonomy](https://codex.wordpress.org/Function_Reference/register_taxonomy), it's possible to provide a callback method that will be invoked when a term is edited, and that will update that term count. This goes in the arg `update_count_callback`. 

Right now, we have this snippet of code in place:
```php
// If we use the nasty SQL query, we need our custom callback. Otherwise, we still need to flush cache.
if ( apply_filters( 'coauthors_plus_should_query_post_author', true ) ) {
	$args['update_count_callback'] = array( $this, '_update_users_posts_count' );
} else {
	add_action( 'edited_term_taxonomy', array( $this, 'action_edited_term_taxonomy_flush_cache' ), 10, 2 );
}
```
and, as far as I know, it is often desired to filter `coauthors_plus_should_query_post_author` to be `false` for performance benefits.

So, in case the arg `update_count_callback` is omitted (and this step is crucial), it will fallback to [`_update_generic_term_count()`](https://developer.wordpress.org/reference/functions/_update_generic_term_count/). That function runs a super-simple query: `SELECT COUNT(*) FROM $wpdb->term_relationships WHERE term_taxonomy_id = %d"`. It just goes and counts links between term and objects, no fancy anything: any post type, any post status... anything that's linked counts. So we have to ask: what post types will have links with `author` terms? Any in `$coauthors_plus->supported_post_types`, as that is used both to display the coauthor box in the edit page AND when running the CLI command `create-terms-for-posts`.

**However**, this is NOT the same behavior achieved by the custom query in `update_author_term_post_count()`. There, [only the `post` post type](https://github.com/Automattic/Co-Authors-Plus/blob/master/co-authors-plus.php#L603) is included in the query. This creates a mismatch between the two counting methods. For example, my setup also has `page` and `download` post types with published items. Those would be counted by the `_update_generic_term_count()`, but not by our custom callback. 

The simplest solution here would be to simply use `$coauthors_plus->supported_post_types` in our custom callback as well. BUT, this would probably break the `count_user_posts()`, which relies on the term count. At that point, the term count would not only contain posts, but any other allowed post type on the site. This would create all sorts of mismatches on the site (`Mine` count in Posts page being wrong; user posts count in Users page being wrong...).

**Comment by rebeccahum** [comment]
> BUT, this would probably break the count_user_posts(), which relies on the term count. At that point, the term count would not only contain posts, but any other allowed post type on the site. 

Could we modify `count_user_posts()` to include only the relevant post type in the second parameter?

**Comment by rebeccahum** [comment]
> BUT, this would probably break the count_user_posts(), which relies on the term count. At that point, the term count would not only contain posts, but any other allowed post type on the site.

Could we modify count_user_posts() to include only the relevant post type in the second parameter?

**Comment by TheCrowned** [comment]
> Could we modify count_user_posts() to include only the relevant post type in the second parameter?

We could, and in fact I am guessing Core's call to `count_user_posts()` in, say, the Posts page, already does that. The filter we are using is the following, and we are only using the first two arguments:
```php
apply_filters( 'get_usernumposts', $count, $userid, $post_type, $public_only );
```
However, if we wanted to use the `$post_type` (and `$public_only`) info, which I really think we should, we couldn't use the term count. Instead, we'd need the custom SQL query with JOINs and all the stuff, and the filter to improve performance would become obsolete. We could cache the results with `wp_cache_set()` though. 

But I'd stress the fact that at this point, `apply_filters( 'coauthors_plus_should_query_post_author', true )` is pretty useless and actually misleading: setting it to `false` break the counting.

**Comment by GaryJones** [comment]
As this hasn't been addressed in 5 years, and the core behaviour is likely to have changed in that time, I'm going to close this one, but future readers are welcome to add further comments if they are affected as well.
