### ISSUE TITLE
co-author input not visible on custom post type

### ISSUE THREAD

**Issue by robert-hopla** [Automattic/Co-Authors-Plus#597]
the plugin works great for me for POSTS and PAGES,

but it won't show on my custom post types. what did I miss?

**Comment by TheCrowned** [comment]
Hi there,
I have tried, but could not reproduce the issue. For example, I have Easy Digital Downloads installed, and the Co-Authors box shows up and works fine in `download` post types. Can you please make sure that the issue occurs even with the latest commit from the master branch?

**Comment by shantanu2704** [comment]
Hey @robert-hopla, just following up. 
are you using the `[coauthors_supported_post_types](https://github.com/Automattic/Co-Authors-Plus/blob/c5c769aa320948acf6c3a8c2b29f7d768b140db4/co-authors-plus.php#L194)` filter to register your custom post type?
you could do this from your theme's functions.php file.
Thanks!

**Comment by mhennessie** [comment]
@shantanu2704 can you elaborate on that filter more, for the life of my I cannot get it to work. I am able to add my custom post type by using an array_push in the plugin files but certainly would prefer adding support using a filter in the functions file.

**Comment by shantanu2704** [comment]
Hi @mhennessie !

Something like this should do the trick:

```
add_filter('coauthors_supported_post_types', function( $post_types ) {
	
		$post_types[] = 'my_custom_post_type';
		return $post_types;
	}
);
```

**Comment by mhennessie** [comment]
@shantanu2704 thank you for the quick response. I found it immediately after I posted.

**Comment by shantanu2704** [comment]
@mhennessie that's great! :slightly_smiling_face:
