### ISSUE TITLE
Not possible to delete users when the guest authors functionality is disabled

### ISSUE THREAD

**Issue by erlendmr** [Automattic/Co-Authors-Plus#601]
It's not possible to delete users if the guest author functionality is disabled.

I get the following PHP error:

`PHP Fatal error: Call to a member function get_guest_author_by() on null in /wp-content/plugins/co-authors-plus/co-authors-plus.php on line 943`.

The guest author functionality is disabled with the following filter:

`add_filter( ‘coauthors_guest_authors_enabled’, ‘__return_false’ );`

**Comment by TheCrowned** [comment]
Thanks for reporting this! I have crafted a fix for the issue and linked it to this issue - while we wait it gets merged, you can apply the patch to your code if you want :)
