### ISSUE TITLE
Author Archive Issue

### ISSUE THREAD

**Issue by dhruveonmars** [Automattic/Co-Authors-Plus#607]
I created an archive for each author using author.php and co-authors plus causes an issue. When I visit an authors archive – /author/nicename, for any user other than the first created user I see an sql error on the page:
`SELECT SQL_CALC_FOUND_ROWS wp_posts.ID FROM wp_posts LEFT JOIN wp_term_relationships AS tr1 ON (wp_posts.ID = tr1.object_id) LEFT JOIN wp_term_taxonomy ON ( tr1.term_taxonomy_id = wp_term_taxonomy.term_taxonomy_id ) WHERE 1=1 AND ((wp_term_taxonomy.taxonomy = 'author' AND wp_term_taxonomy.term_id = '12'07 OR (wp_term_taxonomy.taxonomy = 'author' AND wp_term_taxonomy.term_id = '51'))) AND wp_posts.post_type = 'post' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'acf-disabled' OR wp_posts.post_status = 'private') GROUP BY wp_posts.ID HAVING MAX( IF ( wp_term_taxonomy.taxonomy = 'author', IF ( wp_term_taxonomy.term_id = '51' OR wp_term_taxonomy.term_id = '12',2,1 ),0 ) ) <> 1 ORDER BY wp_posts.post_date DESC LIMIT 0, 9.`

Even when I hide errors from the page, the rest of the page – the WordPress loop that is run on that page returns no posts.

**Comment by xavier-bs** [comment]
I have the same issue on author archive page. To fix it, I have to check if `$current_coauthor_term` is not empty in `co-authors-plus.php` on line 726 (ver 3.3.0)

**Comment by rebeccahum** [comment]
Closing in favour of #573 where it was initially reported.
