### ISSUE TITLE
View co-authors given a post id

### ISSUE THREAD

**Issue by epicfaace** [Automattic/Co-Authors-Plus#608]
Right now, you can only use coauthors_posts_links() to get coauthors for the current post. It would be nice to be able to pass in a post id so you can get the links for an arbitrary post.

**Comment by alexiskulash** [comment]
It looks like `get_coauthor_terms_for_post()` provides this functionality:

https://github.com/Automattic/Co-Authors-Plus/blob/cb77cb36c8cdc615375ca4ad4152a7e6d4635e4b/co-authors-plus.php#L1568-L1602

Could you confirm that's what you're looking for?

**Comment by twitchylegs** [comment]
Any suggestions on how to call get_coauthor_terms_for_post in a shortcode and pass in the post id? The following returns that the function does NOT exist. 
<pre>
function tl_display_authors( $atts ) {
	$atts = shortcode_atts( array(
		'id' => false
	), $atts, 'tfl-display-authors' );

  $post_id = $atts['id'];
  $buffy ='';
  if ( function_exists( 'get_coauthor_terms_for_post' )) {
    $buffy = 'Function exists';
  } else {
    $buffy = 'Function does not exist';
  }
  return $buffy;

}
add_shortcode( 'tl-display-authors', 'tl_display_authors' );

</pre>

**Comment by shantanu2704** [comment]
Hey @twitchylegs!
`get_coauthor_terms_for_post` is a method of the `CoAuthors_Plus()` class.

So you'd have to use [`method_exists()`](http://php.net/manual/en/function.method-exists.php) instead of `function_exists()`.
