### ISSUE TITLE
Author Archive shows only posts associated with the linked user in version 3.3.0

### ISSUE THREAD

**Issue by eflorea** [Automattic/Co-Authors-Plus#611]
When a co-author is linked to a WP_User the archive page only shows the posts associated with that linked account.

The problem was introduced in 3.3.0.

The get_author_term method has been changed and now it's pulling the term from the linked account only
![screen shot 2018-10-04 at 2 35 36 pm](https://user-images.githubusercontent.com/13055601/46504518-f878c200-c7e2-11e8-83b2-13c379570987.png)

so in the where filter the terms are just duplicated ( $author_term === $guest_author_term )

![screen shot 2018-10-04 at 2 37 38 pm](https://user-images.githubusercontent.com/13055601/46504720-9a98aa00-c7e3-11e8-849c-2bc35dc54795.png)

The query looks like this:

![screen shot 2018-10-04 at 2 34 07 pm](https://user-images.githubusercontent.com/13055601/46504605-37a71300-c7e3-11e8-894d-f53fd4d62212.png)

When it should look like this:

![screen shot 2018-10-04 at 2 33 34 pm](https://user-images.githubusercontent.com/13055601/46504597-2eb64180-c7e3-11e8-8b70-5024de4d20f1.png)

**Comment by rebeccahum** [comment]
Hiya @eflorea, we reverted that change -- can you please pull from the latest `master` branch?

**Comment by eflorea** [comment]
Thank you for your quick reply @rebeccahum.

Do you have an ETA of a new release on wordpress.org?
