### ISSUE TITLE
can't use get_avatar() for authors without email address

### ISSUE THREAD

**Issue by ituk** [Automattic/Co-Authors-Plus#616]
Guest authors without email address are not recognized by `get_avatar(get_the_author_meta( 'user_email'), $size)`, which makes sense, but using `get_the_author_meta( 'ID' )` instead doesn't work even for authors with email address.
Steps to reproduce the issue:
 1. add this script outside the loop (in a sidebar of a single page for instance):
`if( function_exists('coauthors') ) :
	$i = new CoAuthorsIterator();
	while( $i->iterate() ) : 
		echo get_avatar( get_the_author_meta( 'user_email' ), apply_filters( 
	endwhile;
endif;`
2. create 2 guest authors: one with avatar (featured image) but without email address. and one with both.
3. assign the new guest authors to a post
4. check the post on the frontend to see if the avatars are shown -> only the avatar of the author who has an email is shown.
5. back in the code, change `user_email` with `ID` and check the post again -> both avatars not shown.

Thanks,
Itamar

**Comment by rebeccahum** [comment]
Closing in favour of #108.
