### ISSUE TITLE
This ugly error in console...

### ISSUE THREAD

**Issue by aldobsom** [Automattic/Co-Authors-Plus#636]
I keep getting this error when I try to add more users to a posting, so I cannot add any :(
`Uncaught SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:2
    at Function.globalEval (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:2)
    at Ha (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:3)
    at a.fn.init.append (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:3)
    at a.fn.init.<anonymous> (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:3)
    at Y (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:3)
    at a.fn.init.html (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:3)
    at i (suggest.min.js?ver=1.1-20110113:1)
    at Object.success (suggest.min.js?ver=1.1-20110113:1)
(anonymous) @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:2
globalEval @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:2
Ha @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:3
append @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:3
(anonymous) @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:3
Y @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:3
html @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:3
i @ suggest.min.js?ver=1.1-20110113:1
(anonymous) @ suggest.min.js?ver=1.1-20110113:1
i @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:2
fireWith @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:2
y @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:4
c @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:4
XMLHttpRequest.send (async)
send @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:4
ajax @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:4
n.(anonymous function) @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:4
f @ suggest.min.js?ver=1.1-20110113:1
setTimeout (async)
e @ suggest.min.js?ver=1.1-20110113:1
dispatch @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:3
r.handle @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,moxiejs,plupload&ver=5.0.1:3`

**Comment by rebeccahum** [comment]
Hi @aldobsom!  Thanks for reporting this, do you have any steps on reproducing?

**Comment by rebeccahum** [comment]
Hi @aldobsom!  Thanks for reporting this, do you have any steps on reproducing?

**Comment by aldobsom** [comment]
hi @rebeccahum. this is what i am trying to findout myself. it seems like there's a plugin or some code interfering with co-author plugin but cannot figure it out,

**Comment by aldobsom** [comment]
hi @rebeccahum. this is what i am trying to findout myself. it seems like there's a plugin or some code interfering with co-author plugin but cannot figure it out,

**Comment by rebeccahum** [comment]
@aldobsom Does this occur for you on a fresh local install of CAP with no other plugins enabled?

**Comment by aldobsom** [comment]
@rebeccahum I found out what was the problem: my code. The plugin is fine :)
