### ISSUE TITLE
Add posts in Mine 

### ISSUE THREAD

**Issue by alexdobsom** [Automattic/Co-Authors-Plus#638]
Display post in Mine also if current user is a multiple author. Is this possible to achieve? 

_Currently in WP if a second author is added to the Co-author metabox that particular post doesn't appear on Mine, only on All._ 

All (1) | Mine | Published (1)

![image](https://user-images.githubusercontent.com/30396343/50218045-44bfb100-0393-11e9-9b0b-4ae1d7799828.png)

**Comment by JoshCalico** [comment]
Shows up just fine on my test user account. Perhaps this was patched?

**Comment by GaryJones** [comment]
I do see that "Mine" doesn't have a count next to it, but it does populate with posts.

<img width="898" alt="Screenshot 2023-07-26 at 17 25 20" src="https://github.com/Automattic/Co-Authors-Plus/assets/88371/00b873f0-112c-4b27-b51e-5413df9e3894">
