### ISSUE TITLE
Guarantee that $wp_query->queried_object_id is an integer

### ISSUE THREAD

**Issue by Biont** [Automattic/Co-Authors-Plus#645]
You're changing the default `queried_object_id` on authors pages to the guest author's ID [here](https://github.com/Automattic/Co-Authors-Plus/blob/b3f34ce6f989f26d25dcad729767bf72be893677/co-authors-plus.php#L1131). At least on my test environment, this is now a string, which conflicts with the declared type of that field which should be an integer:
```
	/**
	 * The ID of the queried object.
	 *
	 * @since 1.5.0
	 * @var int
	 */
	public $queried_object_id;
```

So any code that uses it and relies on the value to be an integer is now prone to throwing a fatal (which is further amplified by static type-hinting becoming more ubiquitous).

Please cast this to `(int)` before setting the variable.

**Comment by rebeccahum** [comment]
@Biont Hi there!  Thanks for reporting this -- feel free to open up a PR with steps on reproducing.

**Comment by GaryJones** [comment]
If it uses a real user account, then I _think_ that this ends up using [`WP_User::get_data_by()`](https://developer.wordpress.org/reference/classes/wp_user/get_data_by/) and that specifically casts the ID to an integer there.

If Guest Authors are enabled, then CAP tries to retrieve them via `user_nicename`, and it looks like [the returned ID is **not** cast to an integer](https://github.com/Automattic/Co-Authors-Plus/blob/cd243202b90a03941e96ea9b2b5ff9fdbe2f6142/php/class-coauthors-guest-authors.php#L914-L921).

Needs more investigation and tests to confirm.
