### ISSUE TITLE
Linked accounts cause author archive query to skip searching for the guest author term

### ISSUE THREAD

**Issue by WPprodigy** [Automattic/Co-Authors-Plus#648]
You end up with queries like this on author archives:

```
SELECT SQL_CALC_FOUND_ROWS wp_posts.ID
FROM wp_posts 
LEFT JOIN wp_term_relationships AS tr1
ON (wp_posts.ID = tr1.object_id)
LEFT JOIN wp_term_taxonomy
ON ( tr1.term_taxonomy_id = wp_term_taxonomy.term_taxonomy_id )
WHERE 1=1 
AND (( 
     (wp_term_taxonomy.taxonomy = 'author' AND wp_term_taxonomy.term_id = '83')
  OR (wp_term_taxonomy.taxonomy = 'author' AND wp_term_taxonomy.term_id = '83')
))
AND wp_posts.post_type = 'post'
AND (wp_posts.post_status = 'publish'
OR wp_posts.post_status = 'private')
GROUP BY wp_posts.ID
HAVING MAX( IF ( wp_term_taxonomy.taxonomy = 'author', IF ( wp_term_taxonomy.term_id = '83'
OR wp_term_taxonomy.term_id = '83'
OR wp_term_taxonomy.term_id = '37',2,1 ),0 ) ) <> 1 
ORDER BY wp_posts.post_date DESC
LIMIT 0, 10
```

Notice how `wp_term_taxonomy.taxonomy = 'author' AND wp_term_taxonomy.term_id = '83'` appears twice, when it should be querying for the guest author term and the linked account term.

_____

## Replicating

1. Create a Guest author account and assign a post to them.
2. Create a normal WP author account.
3. Link the new author account to your guest author.
4. View the guest author's archive page, and notice no posts appear anymore.

____

## Why this is happening

This bug was introduced with the changes to `get_author_term()` here: https://github.com/Automattic/Co-Authors-Plus/pull/438/files

This is because the `posts_where_filter` is set up to query first by the guest author term, and then also by the linked account term if it exists, seen here: https://github.com/Automattic/Co-Authors-Plus/blob/3.3.1/co-authors-plus.php#L674-L685

But since this change, it just ends up querying by the same linked_account term twice.

CC @rebeccahum 

89479-zd and 89781-zd for context

**Comment by rebeccahum** [comment]
@WPprodigy This has been reverted already: https://github.com/Automattic/Co-Authors-Plus/commit/869e0601953357c9da7ef7856060ec8eb3442966
Can you confirm if the issue still occurring via the latest master branch?

**Comment by WPprodigy** [comment]
Right, so the issue does not occur in the master branch. Wasn't sure if we were using that branch differently than release branches.

It'll just be a re-occurring problem until the next release then I suppose.

**Comment by rebeccahum** [comment]
@WPprodigy Nope, next release will be based on `master`.  Closing now, let me know if that is sufficient!
