### ISSUE TITLE
The posts_where regex causes invalid SQL when there are custom post statuses

### ISSUE THREAD

**Issue by WPprodigy** [Automattic/Co-Authors-Plus#651]
This is related to https://github.com/Automattic/Co-Authors-Plus/issues/508 and caused by https://github.com/Automattic/Co-Authors-Plus/pull/576/.

 ## Problem
When there is a custom post status in the query ([such as the one added by bbPress here](https://github.com/wp-plugins/bbpress/blob/master/bbpress.php#L618-L627)), it can make the current regex do unintended things on this line: https://github.com/Automattic/Co-Authors-Plus/blob/b3f34ce6f989f26d25dcad729767bf72be893677/co-authors-plus.php#L740

Example final query after our filter:

```
SELECT SQL_CALC_FOUND_ROWS wp_posts.ID
FROM wp_posts 
LEFT JOIN wp_term_relationships AS tr1
ON (wp_posts.ID = tr1.object_id)
LEFT JOIN wp_term_taxonomy
ON ( tr1.term_taxonomy_id = wp_term_taxonomy.term_taxonomy_id )
WHERE 1=1 
AND ( (wp_term_taxonomy.taxonomy = 'author'
AND wp_term_taxonomy.term_id = '102193'))OR wp_posts.post_status = 'hidden')
GROUP BY wp_posts.ID
HAVING MAX( IF ( wp_term_taxonomy.taxonomy = 'author', IF ( wp_term_taxonomy.term_id = '102193',2,1 ),0 ) ) <> 1 
ORDER BY wp_posts.post_date DESC
LIMIT 0, 20;
```

Note the `OR wp_posts.post_status = 'hidden')` which makes this SQL invalid.

Before the regex replace, the where clause looks like this:

```
" AND wp_posts.post_author IN (456)  AND wp_posts.post_type = 'post' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'closed' OR wp_posts.post_status = 'future' OR wp_posts.post_status = 'draft' OR wp_posts.post_status = 'pending' OR wp_posts.post_status = 'private' OR wp_posts.post_status = 'hidden')"
```

After:

```
" AND ( (wp_term_taxonomy.taxonomy = 'author' AND wp_term_taxonomy.term_id = '102193'))OR wp_posts.post_status = 'hidden')"
```

## Solution

So as you can see, the flaw is assuming that `private` will be the last status in the list. It's not always going to be, as seen here when using bbPress.

We could either be more flexible with the regex and target the last `')`, or perhaps get all of the post_status_types from WP that will be added here and target each of them.

Context: 89781-zd.

**Comment by davidsword** [comment]
> We could either be more flexible with the regex and target the last `')`, 

```php
$where = preg_replace( '/\s\b(?:' . $wpdb->posts . '\.)?post_author\s*IN\s*(.*' . $id . '(?:.*\')?.)/', ' (' . $maybe_both_query . ' ' . $terms_implode . ')', $where, -1 ); #' . $wpdb->postmeta . '.meta_id IS NOT NULL AND 
```

> or perhaps get all of the post_status_types from WP that will be added here and target each of them.

```php
$post_statuses = implode( '|', get_post_stati() );

$where = preg_replace( '/\s\b(?:' . $wpdb->posts . '\.)?post_author\s*IN\s*(.*' . $id . '(?:.*[' . $post_statuses . ']\')?.)/', ' (' . $maybe_both_query . ' ' . $terms_implode . ')', $where, -1 ); #' . $wpdb->postmeta . '.meta_id IS NOT NULL AND 
```

**Comment by WPprodigy** [comment]
Replicating:

1) Activate CAP 3.3.1.
2) Create a normal WP author and author a post with them.
3) View posts and click the "mine column": `https://example.com/wp-admin/edit.php?post_type=post&author=123`

4) Add a custom post status (the params are important, private makes it show up last in the query which triggers this bug):

```
add_action( 'init', 'vip_test_add_post_status' );
function vip_test_add_post_status() {
	register_post_status(
		'vip-status',
		array(
			'label'                     => _x( 'VIP Status', 'post' ),
			'label_count'               => _nx_noop( 'VIP Status <span class="count">(%s)</span>', 'VIP Status <span class="count">(%s)</span>', 'post', 'vip-test' ),
			'private'                    => true,
			'exclude_from_search'       => false,
			'show_in_admin_status_list' => true,
			'show_in_admin_all_list'    => true
		)
	);
}
```

5) Disable querying by post author:

```
add_filter( 'coauthors_plus_should_query_post_author', '__return_false' );
```

6) If needed, replace line 740 (or 713 if you are using 3.3.1 release) with what is in master:

```
$where = preg_replace( '/\s\b(?:' . $wpdb->posts . '\.)?post_author\s*IN\s*(.*' . $id . '(?:.*private\')?.)/', ' (' . $maybe_both_query . ' ' . $terms_implode . ')', $where, -1 ); #' . $wpdb->postmeta . '.meta_id IS NOT NULL AND
```

7) Maybe flush memcache, and reload the "mine" page from step 3. Notice the post doesn't show, and the query is messed up.

**Comment by rebeccahum** [comment]
Closing per #663.
