### ISSUE TITLE
Author's page not showing posts after updating from 3.2.2

### ISSUE THREAD

**Issue by pire** [Automattic/Co-Authors-Plus#668]
This affects versions **3.3.beta**, **3.3.0**, and **3.3.1**.
Have tested on WP 4.9 -> 5.1.1.

After updating from **3.2.2**.

And happens when using **WP_Query**,

```php
$niceName = $curauth->user_nicename;

$args = array(
  'author_name' => $niceName
);

$posts = new WP_Query( $args); 
```

and **get_posts**

```php
$niceName = $curauth->user_nicename;

$args = array(
	'author_name' => $niceName,
);

$posts = get_posts( $args ); ?>
```

Should the posts be queried in a different manner?

Thank you!

**Comment by rebeccahum** [comment]
@pire Hi!  Is this still happening on the `master` branch?

**Comment by pire** [comment]
I just cloned it and it seems to work well on my local WP instance, thank you!!

I had tried 3.2.2, 3.3-beta, 3.3.0, and 3.3.1 from the [releases page](https://github.com/Automattic/Co-Authors-Plus/releases), and the latest version from [WP plugin page](https://wordpress.org/plugins/co-authors-plus/).

Does that mean that the fix will be coming in 3.3.2? 

Thanks again!

**Comment by rebeccahum** [comment]
@pire Yes, a new release of CAP is imminent, thank you for your patience!

**Comment by pire** [comment]
Thank **_you_** !
