### ISSUE TITLE
Avatar images are incorrect in the admin

### ISSUE THREAD

**Issue by rpasillas** [Automattic/Co-Authors-Plus#676]
After updating to the latest version, all of the avatars that display in the admin are incorrect. After some troubleshooting it appears the images are being pulling from the media library instead. For example, user's avatar with ID 100 is using the media image that was uploaded to post 100. This does not affect the front-end, just the admin. This is for all instances of the avatar displayed in the admin, including the top admin tool bar and user edit screens.

I am unable to replicate this outside of the production and staging environments. I've tried replicating using a different WP installation using the same theme and same set of plugins on my local environment.

Commenting out this line in the plugin appears to fix the issue https://github.com/Automattic/Co-Authors-Plus/blob/master/co-authors-plus.php#L1726

**Comment by rpasillas** [comment]
Switching themes to a twenty sixteen/seventeen does not resolve the problem.

**Comment by rebeccahum** [comment]
@rpasillas Hi there! Can you provide steps on how to reproduce?

**Comment by rpasillas** [comment]
@rebeccahum Took quite a while to figure out how to reproduce. 

1. Setup fresh WordPress Site and login.
2. Install Co Authors Plus
3. Note the user's image, if any.
4. Edit the default *Hello World!* post and assign Featured Image.
5. Refresh the admin and now the user image is the same as the Hello World Featured Image.

This behavior is consistent if I create other dummy users and upload a featured image to the post whose ID matches that user ID. To test that:

1. Create a new user (should be created with user ID 2) and note the image, if any.
2. Edit the *Sample Page* page (post ID 2) and assign Featured Image.
3. View the users page in the admin and now the their avatar image has changed to the Sample Page Featured Image.

**Comment by mdrovdahl** [comment]
Seems likely related to https://github.com/Automattic/Co-Authors-Plus/issues/452 and the fix for that in https://github.com/Automattic/Co-Authors-Plus/pull/621

**Comment by sanketio** [comment]
@rebeccahum 

Here https://github.com/Automattic/Co-Authors-Plus/blob/master/co-authors-plus.php#L1725-L1727, we're directly assuming that it'll be a CoAuthor user ID, so whenever any default User ID is passed and let's assume the Post with same ID (same as default User ID) exists, and it has featured thumbnail, then it'll fetch that image instead if User's avatar.

So we need to replace that code with below:
```
public function filter_get_avatar_url( $url, $id ) {

	$guest_author = true;

	if ( isset( $this->guest_authors ) ) {
		$guest_author = $this->guest_authors->get_guest_author_by( 'id', $id );
	}

	if ( $guest_author && has_post_thumbnail( $id ) ) {
		$url = get_the_post_thumbnail_url( $id, $this->gravatar_size );
	}

	return $url;
}
```

Let me know if you've any other alternative or suggestion.

cc: @rpasillas @mdrovdahl

**Comment by rebeccahum** [comment]
@sanketio Feel free to open a PR!

**Comment by rebeccahum** [comment]
Looks also if the guest author ID is the same as the user ID, the avatar is incorrect as well for the user...
