### ISSUE TITLE
Question: can you clarify the force-push done recently here?

### ISSUE THREAD

**Issue by goldenapples** [Automattic/Co-Authors-Plus#688]
We've been using this plugin as a submodule in project, and our builds have started failing recently due to a missing commit hash. Comparing the repository I have checked out to the current state, the only real difference I'm seeing is that the `wpcom-helper.php` file has been removed.

Is this the case, and if so, is it the only change here?

**Comment by rebeccahum** [comment]
@goldenapples That is correct.

**Comment by goldenapples** [comment]
Thanks! I'm wondering: would it be helpful to announce the change with an email or something? This plugin is still pretty widely used and I think many other older projects using it are likely to have build failures as a result...

**Comment by rebeccahum** [comment]
Hi @goldenapples, to prevent a situation like this from happening, we recommend using subtrees over submodules, as they do not have a strict upstream dependency.
