### ISSUE TITLE
Deleting a user can mistakenly assign new bylines

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/Co-Authors-Plus#69]
To reproduce:
- User A creates a new post but publishes it under Guest Author A byline
- Admin deletes User A and assigns all of their posts to User B
- Post with Guest Author A byline will now get User B added to the byline too.

The culprit is:

`$post_ids = $wpdb->get_col( $wpdb->prepare( "SELECT ID FROM $wpdb->posts WHERE post_author = %d", $delete_id ) );`

This gets post IDs where the user doesn't necessarily have the byline.

**Comment by rebeccahum** [comment]
This is also because guest author account A (previously linked to user A) still exists.

When we delete users linked to guest author accounts, perhaps we can add a default option to keeping existing post bylines mapped to the guest author account.

**Comment by rebeccahum** [comment]
This is also because guest author account A (previously linked to user A) still exists.

When we delete users linked to guest author accounts, perhaps we can add a default option to keeping existing post bylines mapped to the guest author account.

**Comment by rebeccahum** [comment]
This is also because guest author account A (previously linked to user A) still exists.

When we delete users linked to guest author accounts, perhaps we can add a default option to keeping existing post bylines mapped to the guest author account.

**Comment by rebeccahum** [comment]
This is also because guest author account A (previously linked to user A) still exists.

When we delete users linked to guest author accounts, perhaps we can add a default option to keeping existing post bylines mapped to the guest author account.

**Comment by philipjohn** [comment]
Fixed by #414
