### ISSUE TITLE
302 redirect to /404 for non-existent paged Author archive

### ISSUE THREAD

**Issue by kclarke10** [Automattic/Co-Authors-Plus#703]
I'm talking about non-existent paged Author archives -> (like for example: https://domain.com/author/mike/page/15/, where mike has only 100 posts with wp set to 10 posts per page)

When Co Authors is enabled, instead of just doing a 404 on that URL, it sends a 302 redirect to domain.com/404 which then returns a 404 code.  

Only noticed this because Google has been trying to crawling domain.com/404 thousands of times when it decides to probe these paged archives that don't exist and have never existed.   This wastes crawl budget.

**Comment by GaryJones** [comment]
Fixed with #874.
