### ISSUE TITLE
Move the Authors metabox to the sidebar

### ISSUE THREAD

**Issue by garretthyder** [Automattic/Co-Authors-Plus#705]
Hello,

It would be nice if for both the classic editor and block editor (Gutenberg) that the Authors meta box would appear in the side instead of in the body. 

The default Author metabox is in the side so the replacement one should also be placed there. 

On the classic editor it's simple to drag into the sidebar, but with Gutenberg that's not possible.

Thanks

**Comment by garrett-eclipse** [comment]
Oop, I'll minorly correct my 'but with Gutenberg that's not possible.' statement. It's possible just really hard as there's a bug that as you move to the sidebar the page keeps expanding, but with some fiddling you can get it into the sidebar.

Would just be nice to have that the default.

**Comment by garrett-eclipse** [comment]
I just wanted to refer back to the Gutenberg issue which makes it hard to move the metabox into the sidebar;
https://github.com/WordPress/gutenberg/issues/17432

**Comment by ckoerner** [comment]
This is a usability issue for folks new to CAP, but not WordPress. Their experience tells them that authorship is managed in the sidebar. You have to know (or instruct folks) to school below your content to manage authors.

**Comment by TheCrowned** [comment]
I agree. Especially with Gutenberg, the Coauthors box is the only below the content window, all defaults boxes are on the side. And with the classical editor it's good for it to be on the side anyway, since the default _Authors_ box is on the side in the first place.
I will take this and submit a PR.

**Comment by TheCrowned** [comment]
(Notice that even when/if the PR will be merged, current metabox location won't change if you already have CAP installed and you dragged it even slightly, as WP will have recorded the current location as your custom decision.)

**Comment by garretthyder** [comment]
Nice @TheCrowned that's awesome, patch looks good to me and works so hope it makes it in. As to existing users as long as it's mentioned in the changelog hopefully those who care can clear their settings or update to use 'side'.
