### ISSUE TITLE
Add authors in other plugin

### ISSUE THREAD

**Issue by PAKOTxx** [Automattic/Co-Authors-Plus#711]
Hello,
I need to add multiple authors to post via some function in other plugin. 
Using wp-admin it's work well, but I need do it via other function(database migrating).
So I have PostID and some array of authors ID, how I can add them to post? 
I found function coauthors_set_post_author_field, but not sure how I should use it in other plugin.
Thanks for the help

**Comment by lubieowoce** [comment]
i think you want `CoAuthorsPlus::add_coauthors`:
```php
function add_coauthors($post_id, $coauthors, $append = false, $query_type = 'user_nicename')
```
so i'm guessing you'd do something like this (not exactly sure how `$query_type` works though)

```php
global $coauthors_plus;
if (isset($coauthors_plus)) {
    $coauthors_plus->add_coauthors($your_post, $your_coauthor_ids, true, 'ID');
}
```
