### ISSUE TITLE
XML-RPC support

### ISSUE THREAD

**Issue by mjangda** [Automattic/Co-Authors-Plus#72]
I should be able to assign co-authors via the standard `newPost` and `updatePost` XML-RPC methods. Or, we could just have custom endpoints.

**Comment by BrekiTomasson** [comment]
Just bumping as a reminder. This is still fairly high up on the list of things this plugin should be able to do.

**Comment by joshbetz** [comment]
Let's create custom wp-api endpoints instead :)

**Comment by BrekiTomasson** [comment]
That's an even better idea. Anybody working on this already?

**Comment by fabn** [comment]
Any news on this? I need to assign coauthors using XMLRPC api and I haven't found a way to do that.

Any workaround?

**Comment by philipjohn** [comment]
Closing in favour of #321
