### ISSUE TITLE
Add normal users?

### ISSUE THREAD

**Issue by strarsis** [Automattic/Co-Authors-Plus#722]
Is it possible to add "normal" WordPress users as author of a post?
The search suggestion doesn't seem to search for normal users but rather in the `author` taxonomy,
hence it won't find normal WordPress users.
The existing owner of the post who is a normal WordPress user, is already listed there, 
but can't be found by the search either.

**Comment by rebeccahum** [comment]
> Is it possible to add "normal" WordPress users as author of a post?

Yes, this should be possible.  Are you able to provide any further details on how to reproduce on a vanilla install?

**Comment by strarsis** [comment]
@rebeccahum: Well, I have to create a guest user per normal WordPress user, also with different username. This can become very complicated.

**Comment by rebeccahum** [comment]
I'm thinking that you may have to run a backfill on authors created before CAP was installed to create their respective terms: https://github.com/Automattic/Co-Authors-Plus/blob/221e4df88d65b1ba2eb4467d16e4ba74d82f37c9/php/class-wp-cli.php#L53

`wp co-authors-plus create-terms-for-posts`
