### ISSUE TITLE
Doesn't work with Newspaper Theme

### ISSUE THREAD

**Issue by kamlesh08** [Automattic/Co-Authors-Plus#734]
Co-Authors Plus Plugin doesn't work with Newspaper Theme.
While I am able to add 2 authors to the post, only 1 author is visible when I publish the post. 
Thus, dissolving the point of using the Co-Authors-Plugin

**Comment by rebeccahum** [comment]
Hi @kamlesh08, are you finding that the author is not visible on the published post itself or on the backend?

**Comment by kamlesh08** [comment]
Hello @rebeccahum, The 2 authors which I added in the post didn't appear when I published the post.

**Comment by rebeccahum** [comment]
@kamlesh08 You will most likely need to modify the theme to account for the extra authors via the template tags: https://github.com/Automattic/Co-Authors-Plus/blob/master/template-tags.php

**Comment by kamlesh08** [comment]
@rebeccahum thanks! I'll have a look at the code snippet and will update you on how it turns out.
Thanks!
