### ISSUE TITLE
Co-Author Plus spamming Simple History plugin, is this a but or a feature?

### ISSUE THREAD

**Issue by Peterr-K** [Automattic/Co-Authors-Plus#753]
Hi

I have installed this plugin https://en.wordpress.org/plugins/simple-history/

When I'm just searching for a co-author (not adding one) there is spam of messages in this history plugin, is this actually ok? can this be fixed? is there anything to fix?

thanks

![image](https://user-images.githubusercontent.com/56595831/108866232-4aa92080-75f4-11eb-9b24-ae8f9c9b7385.png)

**Comment by rebeccahum** [comment]
@Peterr-K It would be best to bring this up with the Simple History plugin author since this issue is occurring there.

**Comment by rebeccahum** [comment]
@Peterr-K Hey there! It would be best to bring this up with the Simple History plugin author since the issue is occurring there.

**Comment by Peterr-K** [comment]
ok they created this https://github.com/bonny/WordPress-Simple-History/issues/238
