### ISSUE TITLE
Some Contributors and Guest Author names are not loading

### ISSUE THREAD

**Issue by iasgharalikhan** [Automattic/Co-Authors-Plus#761]
Hi, 
We have some guest authors who are not reflecting in the plugin block.

Can you please look into this.

**Comment by lukaszange** [comment]
I also have this error on my productive version, but not yet on the local one to reproduce... The error has been occurring since the update to version #760 (Version 3.4.4).

**More detailed description**
1. Install CAP Version 3.4.4
2. Edit a existing post or create a new one
3. Try to add a co author to this specific post
4. The AJAX suggest box returns the error "Sorry, no matching authors found."

**Circumstances already tested**
The error seems only to be happening on "real" users - guest authors can still be selected.

**Comment by rebeccahum** [comment]
@lukaszange Does rolling back to 3.4.2 fix the issue?

**Comment by iasgharalikhan** [comment]
> @lukaszange Does rolling back to 3.4.2 fix the issue?

Roll back fixed it for me

**Comment by rebeccahum** [comment]
I'm not able to reproduce on a fresh install, whether the real user has been created before CAP was installed or after. Any details on reproducing locally would be great.

**Comment by iasgharalikhan** [comment]
> I'm not able to reproduce on a fresh install, whether the real user has been created before CAP was installed or after. Any details on reproducing locally would be great.

So, we have been using CAP for almost 6 months and all the versions in that time period.

The problem is not specific to older or newer profiles, cause some of the newer users are displaying in the updated version.

But only a few of users are left out.

I can share screenshots if you need some details

**Comment by rebeccahum** [comment]
@iasgharalikhan If it's a few of them being left out, are you able to provide the usernames as examples?

**Comment by iasgharalikhan** [comment]
M A Siraj
PTI
IANS
ANI

Are some user names we had which were not displaying, since we rolled back to the previous version. I don't think I have any more details on this.

**Comment by lethalmiko** [comment]
I installed plugin months after users were created and already existing. Plugin has worked fine for over 4 years until last week Friday 26th March 2021 when it stopped. I searched for 4 different existing users but no results. Rolling back to 3.4.3 solved the problem. One user on the thread I started on wordpress.org wrote this:
-------
giuliovale (@giuliovale)
20 hours, 57 minutes ago
Problem came from change of:

$found_user = $this->get_coauthor_by( ‘user_nicename’, $found_term->slug );

to

$found_user = $this->get_coauthor_by( ‘user_nicename’, $found_term->name );

**Comment by jeffersonrabb** [comment]
The issue has something to do with users with spaces in the username.

Steps to repro:

- Spin up a new WordPress site.
- Install Co-Authors Plus 3.4.4 and WP Rollback.
- Create two WordPress users (not Guest Authors). Username "Test Author" for one and "Test_Writer" for the other.
- Edit a Post, in Authors UI search for "Test". "Test_Writer" is returned but not "Test Author"
- Roll CAP back to 3.4.3
- Repeat the search, and this time you should get both. 

I agree with @lethalmiko about the cause, which was introduced in https://github.com/Automattic/Co-Authors-Plus/pull/744

Reverting that change fixes the issue.

cc: @avcascade

**Comment by rebeccahum** [comment]
Thanks, reverting in #763.
