### ISSUE TITLE
Switch from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by nielslange** [Automattic/Co-Authors-Plus#777]
~At the moment, this repo is using Travis CI, which runs rather slow. This issue aims to switch from Travis CI to Circle CI.~
~Example config file: https://github.com/Automattic/vip-go-mu-plugins/blob/master/.circleci/config.yml~

Update: 

At the moment, this repo is using Travis CI, which runs rather slow. This issue aims to switch from Travis CI to GitHub Actions.

Scope:

- [ ] Run plugin against single- and multisite
- [x] Run plugin against PHPCS (PHP 5.6 - PHP 8.0)
- [x] Run plugin against PHPUnit (PHP 7.1 - PHP 7.4)

**Comment by rebeccahum** [comment]
Instead of CircleCI, I think GitHub actions would be the way to go.

**Comment by nielslange** [comment]
> Instead of CircleCI, I think GitHub actions would be the way to go.

Sounds good. That way, we can also automatically 10up's [WordPress.org Plugin Deploy](https://github.com/10up/action-wordpress-plugin-deploy) action.
