### ISSUE TITLE
CSS hack for hiding Gutenberg post_author no longer works.

### ISSUE THREAD

**Issue by scofennell** [Automattic/Co-Authors-Plus#791]
CAP uses this CSS:

`/** Block Editor Hack for 5.0: Hide the core author input **/
.block-editor label[for^="post-author-selector-"],
.block-editor select[id^="post-author-selector-"] {
	display: none;
}
`

In order to hide the core post_author selector in Gutenberg.  See https://github.com/Automattic/Co-Authors-Plus/pull/630 .

However, at some point this CSS stopped working, because the markup for the post_author changed, see screenshot:

<img width="2048" alt="Screen Shot 2021-05-20 at 10 36 44 AM" src="https://user-images.githubusercontent.com/1585637/118999078-f645e080-b957-11eb-8e70-b1b76eedd737.png">

It looks like the correct CSS would be:

`/** Block Editor Hack for 5.0: Hide the core author input **/
.post-author-selector {
	display: none;
}
`

This is important because users are trying to use the post_author field, and it's not working.

**Comment by rebeccahum** [comment]
@nielslange Looks like this was introduced in 5.6 — can you look at getting this updated?
