### ISSUE TITLE
Version 3.4.9 Breaks Author Post Lists

### ISSUE THREAD

**Issue by gregarios** [Automattic/Co-Authors-Plus#815]
I'm running MySQL 10.5.12-MariaDB with the latest Wordpress 5.8 on CentOS 7.9

Only since version 3.4.9 I'm getting this error when the theme tries to display authors' posts on a page. The page no longer shows the list.

`mod_fcgid: stderr: WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GROUP BY 4HsBd_posts.ID HAVING MAX( IF ( 4HsBd_term_taxonomy.taxonomy = 'auth...' at line 1 for query SELECT SQL_CALC_FOUND_ROWS 4HsBd_posts.ID FROM 4HsBd_posts LEFT JOIN 4HsBd_term_relationships AS tr1 ON (4HsBd_posts.ID = tr1.object_id) LEFT JOIN 4HsBd_term_taxonomy ON ( tr1.term_taxonomy_id = 4HsBd_term_taxonomy.term_taxonomy_id ) WHERE 1=1 AND (( (4HsBd_term_taxonomy.taxonomy = 'author' AND 4HsBd_term_taxonomy.term_id = '153')) AND 4HsBd_posts.post_type = 'post' AND (4HsBd_posts.post_status = 'publish' OR 4HsBd_posts.post_status = 'private') GROUP BY 4HsBd_posts.ID HAVING MAX( IF ( 4HsBd_term_taxonomy.taxonomy = 'author', IF ( 4HsBd_term_taxonomy.term_id = '153' OR 4HsBd_term_taxonomy.term_id = '66',2,1 ),0 ) ) <> 1 ORDER BY 4HsBd_posts.post_date DESC LIMIT 0, 30 made by require('wp-blog-header.php'), wp, WP->main, WP->query_posts, WP_Query->query, WP_Query->get_posts,`

**Comment by douglas-johnson** [comment]
I think I'm seeing the same thing. Here's my output from Query Monitor this morning after updating to 3.4.9

<img width="1243" alt="Screen Shot 2021-08-12 at 9 22 11 AM" src="https://user-images.githubusercontent.com/226381/129206628-384be994-2b88-47be-8903-fc3d04e667f3.png">
<img width="1250" alt="Screen Shot 2021-08-12 at 9 14 10 AM" src="https://user-images.githubusercontent.com/226381/129206630-cd442a39-edb8-4545-b083-2c92f1fb41dc.png">

**Comment by rebeccahum** [comment]
Can you tell me if reverting [this PR](https://github.com/Automattic/Co-Authors-Plus/pull/686) fixes the issue at hand?

**Comment by douglas-johnson** [comment]
@rebeccahum Yes, that worked for me.

Steps I took:
- Updated to 3.4.9
- Recreated issue in WP Admin
- Replaced line 746 in co-authors-plus.php with previous value
- Issue resolved
