### ISSUE TITLE
CSS hack for hiding Gutenberg post_author no longer works redux

### ISSUE THREAD

**Issue by gamebits** [Automattic/Co-Authors-Plus#825]
This is a recurrence of https://github.com/Automattic/Co-Authors-Plus/issues/791 that was addressed in https://github.com/Automattic/Co-Authors-Plus/pull/793. The "Author" dropdown is again being displayed, despite Co-Authors Plus being active and inserting its own "Authors" field.

![wp-author](https://user-images.githubusercontent.com/12199101/138466406-ea621d4f-8a07-4d5b-9183-9b19be8cfb13.jpg)

![cap-authors](https://user-images.githubusercontent.com/12199101/138466412-275d0618-3f5a-4b9c-a6c0-18057ef38edd.jpg)

I've thus far been unsuccessful in determining what change to WordPress or Gutenberg broke the prior fix, or what new CSS should be targeted.

![wp-authors-css](https://user-images.githubusercontent.com/12199101/138466782-0ae8854f-85c4-4723-8d61-03e02d8e201f.jpg)

**Comment by lschuyler** [comment]
With the changes to the author combobox in the editor from #790, I don't think this will be needed anymore, and the CSS hack introduced in #791 can likely be removed too. I'll test!

**Comment by lschuyler** [comment]
Confirmed. We aren't using the author box from core anymore, so this is no longer a relevant issue.

CSS hack removed in #847.
