### ISSUE TITLE
PHP Fatal error: Uncaught Error: Call to undefined function CoAuthors\API\use_block_editor_for_post() in /wp-content/plugins/co-authors-plus/php/class-coauthors-endpoint.php:292

### ISSUE THREAD

**Issue by bransinanderson** [Automattic/Co-Authors-Plus#842]
Wordpress version 5.9.2
Co-Author-Plus version 3.5

When editing a page entry, located in the sidebar under "Page Attributes". Modifying the value of the pages parent we are receiving Error 500 with xhr request:
/wp-json/wp/v2/pages?context=edit&per_page=100&exclude=12345&parent_exclude=12345&orderby=menu_order&order=asc&_fields=id%2Ctitle%2Cparent&_locale=user

Error log
`PHP Fatal error: Uncaught Error: Call to undefined function CoAuthors\API\use_block_editor_for_post() in /wp-content/plugins/co-authors-plus/php/class-coauthors-endpoint.php:292`

Appears to be a name space issue

**Comment by rebeccahum** [comment]
Thanks for reporting. We'll get this fixed out ASAP.
