### ISSUE TITLE
Include the changelog in the readme.txt for the WP.org release

### ISSUE THREAD

**Issue by garubi** [Automattic/Co-Authors-Plus#846]
Please include the changelog in the readme.txt file when pushing a new release to WP.org repository.
It's a common good practice, why don't you follow this?

**Comment by rebeccahum** [comment]
Thanks for your suggestion! We originally had it there but it was getting too lengthy, which is why we moved it all to the CHANGELOG.md. However, going forward, we can put the changelog just for the latest release on the readme.txt if that sounds good to you? 🙂

**Comment by garubi** [comment]
Tanks for the replay!
Yes, the changelog for the latest release would be adeguate: I think that the need is to know wha't changed before hitting that "update now" button :-D
Or, even simpler, a link to https://github.com/Automattic/Co-Authors-Plus/blob/master/CHANGELOG.md (so you don't have to update the readme.txt)
Anything will be better than no changelog ;-)

**Comment by rebeccahum** [comment]
cc @lschuyler for the next release
