### ISSUE TITLE
Author emails shown in term description through WP REST API

### ISSUE THREAD

**Issue by douglas-johnson** [Automattic/Co-Authors-Plus#850]
I am concerned that because author emails are included in the term description, that makes all author email addresses publicly available through the REST API.

In this screenshot you can see a user with no permissions making a request to `/wp-json/wp/v2/coauthors/` on a local environment running a fresh install of WordPress 5.9.3 with Co-Authors Plus 3.5.1 and no other plugins.

<img width="1020" alt="cap-rest-api" src="https://user-images.githubusercontent.com/226381/170702412-70acc6cf-c6f9-468d-91cb-9abae06ddce6.png">

**Comment by rebeccahum** [comment]
Please take a look @lschuyler when you get a chance. Looks like this was introduced in 3.5

**Comment by rebeccahum** [comment]
Fixed in #851.
