### ISSUE TITLE
Author selection XHR is slow/not working

### ISSUE THREAD

**Issue by Fabmilan** [Automattic/Co-Authors-Plus#855]
Hey there!

I don't know why, but your plugin has stop working. I can't change author (the field is disabled) and the autocomplete input field (Select An Author) not working anymore.

I have been using your plugin for 1 year and everything was working fine until then. Did you change something ?

Thx.

**Comment by Fabmilan** [comment]
![image](https://user-images.githubusercontent.com/8641854/172570708-2996b0d7-0871-4111-89d7-9b8ba4601b1f.png)

**Comment by rebeccahum** [comment]
@Fabmilan Do you have more details? What Co-Authors Plus version are you currently using? Was this after the latest update? What WordPress version are you running?

**Comment by Fabmilan** [comment]
> 

Hey thx for the reply.
I'm using the latest version of Co-Authors Plus  3.5.2  / Wordpress 6.0

In fact, the plugin is working, it is just the xhr who is very very slow and that gives me the authors, not co-authors :/

I don't know what happens here ^^

**Comment by lschuyler** [comment]
Hi @Fabmilan,

I've been unable to replicate this. Are there any corresponding errors showing in your browser's JavaScript console that could lend any clues as to why you are experiencing that author field as disabled? Thanks!

**Comment by Fabmilan** [comment]
I'm not the only one with this issue see plugin reviews: https://fr.wordpress.org/plugins/co-authors-plus/#reviews

**Comment by Antonio-Laguna** [comment]
I reckon this is due to this https://github.com/Automattic/Co-Authors-Plus/pull/851

**Comment by lschuyler** [comment]
@Fabmilan - We are still working to replicate your experience so we can fix this. Could you tell us a bit more about your Co-Authors Plus setup?
- Do you have terms in place for all authors? (Have you run the `create-terms-for-posts` CLI?)
- Or are you relying on the `guest-author` custom post type?
- Are you using the `coauthors_plus_should_query_post_author` or `coauthors_count_published_post_types` mentioned in the FAQ? https://github.com/Automattic/Co-Authors-Plus#frequently-asked-questions
- Are your co-authors linked to WordPress user accounts?

Thanks!

**Comment by Fabmilan** [comment]
Hello @GaryJones,

The issue is still here, co-authors (guest authors) not showing up in the listbox :(
I have a guest called Sandra
I type San or san or sandra... nothing shows up :(

**Comment by Fabmilan** [comment]
Hello @GaryJones,

I'm sorry, but it is not working.
I have a guest author called Sandra
I begin to type San or san even Sandra or sandra... but nothing shows up :(

**Comment by GaryJones** [comment]
<img width="268" alt="Screenshot 2023-07-27 at 09 21 06" src="https://github.com/Automattic/Co-Authors-Plus/assets/88371/d365b8ef-2268-4d9d-95b6-eb67c4caa6a7">

You may have a plugin conflict, or the REST API responses may be blocked. I'm going to need more information.

- Do you see any JavaScript errors in the browser developer console?
- Can you recreate the issue on a non-production site, and deactivate the other plugins and use a core theme to check?
- Can you please also confirm your PHP, WP, and plugin versions?
- Can you see XHR requests being made (Network tab of the console) when you type each character? Do they have responses? 

<img width="1332" alt="Screenshot 2023-07-27 at 09 24 57" src="https://github.com/Automattic/Co-Authors-Plus/assets/88371/e3f58bc9-2207-43d1-8b1f-c88c3d84062d">

<img width="780" alt="Screenshot 2023-07-27 at 09 27 53" src="https://github.com/Automattic/Co-Authors-Plus/assets/88371/a7ce2698-1a08-4016-a894-78e36e681707">

**Comment by Fabmilan** [comment]
* Do you see any JavaScript errors in the browser developer console?
No

* Can you recreate the issue on a non-production site, and deactivate the other plugins and use a core theme to check?
I tested  in a sandbox and it works... Good call.

* Can you please also confirm your PHP, WP, and plugin versions?
7.4 / 6.2.2 / 3.15.11

* Can you see XHR requests being made (Network tab of the console) when you type each character? Do they have responses?
I have the XHR request but response is empty :/
This endpoint is called : https://www.1jour1actu.com/wp-json/coauthors/v1/search/?q=san&existing_authors=admin-milan&_locale=user
And I have this response :
`{"code":"rest_forbidden","message":"D\u00e9sol\u00e9, vous n\u2019avez pas l\u2019autorisation de faire cela.","data":{"status":401}}`

The role of the user calling this route is Administrator.

API REST works for this website : https://www.1jour1actu.com/wp-json/wp/v2/posts

I have no clue of what is going on :D 

Thank you for your help

**Comment by Fabmilan** [comment]
FYI, here is what I checked and not working:

- Desactivate all plugin (except coauthor of course :) )
- Delete all plugin 
- Delete my current theme (to not have specific functions.php)
- Use twentythree theme

And with a fresh install (WP 6.2.2, basic + coauthors), it works. 

I'm thinking, is something in the database (eg: wp-options) could go wrong with api-rest ?

thx again ;)

**Comment by GaryJones** [comment]
The JSON response suggests it's an authorisation thing. The request headers should include a nonce. Maybe one of your other plugins is amending that nonce, or doing something that makes the login cookie invalid. At this point, you'll need to enable your plugins and theme one by one to narrow down further what the culprit is.

(If you try to hit the REST API endpoint in a browser directly, then it's expected to fail as that request won't include the nonce.)

From a CAP point-of-view, the plugin is working, so I'm going to close this issue out but feel free to add more information on what you find if you can pinpoint the source of the problem.
