### ISSUE TITLE
Incorrect link with Jetpack social

### ISSUE THREAD

**Issue by ferllings** [Automattic/Co-Authors-Plus#857]
Hello,

When the co-author plugin is enabled, the Jetpack Twitter social urls are incorrectly pointing to the incorrect post.
See https://www.ejiltalk.org/the-far-reaching-us-proposals-to-amend-the-international-health-regulations-at-the-upcoming-75th-world-health-assembly-a-call-for-attention/

When the co-author plugin is disabled, everything is back to normal.
I tested older versions of the plugin, with similar result.

I don’t know how the co-author plugin can affect the post urls used by Jetpack, so if you could point me to the right direction to debug this problem.
Thanks,

**Comment by lschuyler** [comment]
Hi @ferllings,

From the 'View Source' on your page, I can see Jetpack's Sharing module is using the wrong value for `$post->ID` when it is preparing the markup of the sharing buttons. Here's the line in Jetpack's code where those buttons are generated - [here](https://github.com/Automattic/jetpack/blob/2447e267e40f2d133a5c15c2320b776e4c395ec8/projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php#L1196).

I'm not able to replicate this when testing on a site with just Co-Authors Plus and Jetpack installed. 

It sounds like there is a query in a loop somewhere on your site that doesn't use a [wp_reset_postdata](https://developer.wordpress.org/reference/functions/wp_reset_postdata/) after its loop to restore the proper post object for the post being displayed.

In looking at a few of your posts, there seems to be a pattern where the wrong post ID being used, always matches a post in the "More articles by" sidebar. Where this sidebar doesn't appear, the share buttons are correct. Take a look into the code for that sidebar element and see if there is a `wp_reset_postdata` used, and if not, see if you can add it to test.

Let us know how you make out!

**Comment by ferllings** [comment]
That's very helpful.
I'm not the creator of the theme, but I now know what to look for.
Thanks.

**Comment by ferllings** [comment]
I don't know exactly how it related to your plugin, but, with your help, I was able to find the problematic loop and fix it Thanks !!!
