### ISSUE TITLE
Suggestion: change GitHub readme.md to use headings for FAQ items instead of bullets

### ISSUE THREAD

**Issue by benlk** [Automattic/Co-Authors-Plus#867]
The current version of https://github.com/Automattic/Co-Authors-Plus/blob/master/README.md uses bullet points as "headings" for FAQ questions. On GitHub, this means that [the automated Table of Contents support](https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/) doesn't pick up on the FAQ items, making it hard/impossible to link directly to the FAQ items.

If README.md is not generated by an automated process, please update the file to use `###` instead of `*` for these items: https://github.com/Automattic/Co-Authors-Plus/blob/master/README.md?plain=1#L23

If README.md is generated by an automated process, please investigate what that automated process supports in terms of translating from wordpress.org readme.txt files to the Markdown format used on GitHub.

**Comment by rebeccahum** [comment]
Fixed in #884
