### ISSUE TITLE
CLI Command: create_guest_author

### ISSUE THREAD

**Issue by oscarssanchez** [Automattic/Co-Authors-Plus#875]
Hello,

With a client who didn't have their data in appropriate CSV format we could've used a command that creates a new user with CLI. In the end, we formatted the data but I see people being in the same scenario. It would be helpful if they could just loop through a text file while reading lines, assign values to variables and repeat the same command. Also it would be helpful for people who just want to create a guest author from CLI.

I'd be happy to craft a PR if this is something you would consider. Thanks!

**Comment by rebeccahum** [comment]
@oscarssanchez Yes, a PR is always welcome!

**Comment by oscarssanchez** [comment]
Thanks @rebeccahum I opened https://github.com/Automattic/Co-Authors-Plus/pull/879 in the meantime, solving that problem first would be great before doing this one!
