### ISSUE TITLE
Installing CAP via git will fatal error without a composer install (breaking change in 3.5.5)

### ISSUE THREAD

**Issue by mboynes** [Automattic/Co-Authors-Plus#897]
3.5.5 carried a breaking change not included in the release notes, so I suspect that this was unintentional. The main plugin file now [requires a composer autoloader](https://github.com/Automattic/Co-Authors-Plus/blob/bc70909c8e22db21b9724494192719df8cb002b3/co-authors-plus.php#L37). Prior to 3.5.5, a `composer install` was only required for development on the plugin; now it is a prerequisite to run the plugin. This is not documented in the README's installation steps. Any site including CAP as a submodule or subtree would start to fatal if updated.

Since the autoloader is only being included for one class, which is then immediately called, it serves no benefit (in fact, it's instead ever-so-slightly _less_ performant). Given the cost:benefit ratio in this instance, I would recommend removing the autoloader in favor of requiring the class directly.

A site installing CAP via the dot-org plugin repo would be unaffected, since the deployment to the dot-org repo runs a `composer install`.

**Comment by rebeccahum** [comment]
@leogermani Can you take this one?

**Comment by leogermani** [comment]
Yes, I agree with that. I'll submit a PR

**Comment by leogermani** [comment]
> Since the autoloader is only being included for one class, which is then immediately called, it serves no benefit

Actually its main purpose was to autoload the class declared in `integrations/yoast/class-coauthor.php`. That class is only used in certain situations and can only be required when Yoast is active. That's why I added the `require` statement inside some conditions in the PR above.
