### ISSUE TITLE
User Deprecated: Function Yoast\WP\SEO\Config\Schema_Types::get_article_type_options_values is <strong>deprecated</strong> since version WPSEO 19.12 with no alternative available.

### ISSUE THREAD

**Issue by lkraav** [Automattic/Co-Authors-Plus#901]
Looks like we'll need to upgrade integration here.

Sentry traceback: https://sentry.io/share/issue/3dcf6783f25747faaf7c35abfad13596/

**Comment by rebeccahum** [comment]
@leogermani Do you have time to look into this?

**Comment by lkraav** [comment]
PS this is a heavy log spammer.

**Comment by leogermani** [comment]
Yes, I'll have a look as soon as I can

**Comment by wprosrb** [comment]
What is the schedule for releasing the next version to the WordPress plugin repo? I'm looking forward to reducing the noise in my logs with this fix

**Comment by rebeccahum** [comment]
@wprosrb Hello! I will look into doing this tomorrow.
