### ISSUE TITLE
`post_author` not updated properly if assigning a new WP user

### ISSUE THREAD

**Issue by dkoo** [Automattic/Co-Authors-Plus#903]
If updating a post's author and assigning a WP user (not a CAP guest author), the `post_author` field isn't updated even though the `author` taxonomy term is updated. Because the term is updated properly, the post will render with the correct author byline, but the post will not appear in any WP queries targeting the `post_author` ID or name. Verified in v3.5.6.

To replicate:

1. Publish a post assigned to the site's default author.
2. Using the CAP sidebar UI, add another WP user (not guest author) and remove the original author. Update the post.
3. View the post and observe that the new WP user is shown as the byline.
4. However, using WP CLI, `get` the post (`$ wp post get <ID>`) and observe that the `post_author` field still shows the default author's ID, not the second WP user's.

**Comment by oscarssanchez** [comment]
I couldn't reproduce this locally. For me it is updating the `post_author` field with the correct ID as long as the author exists as a WP User.

**Comment by dkoo** [comment]
I'm still able to replicate locally and on other staging sites. On some sites I had to repeat step 2 with another WP user before the `post_author` field got "stuck", but it's easily reproducible.

**Comment by GaryJones** [comment]
I've been able to replicate this. So far, the fix in #988 seems to be working.
