### ISSUE TITLE
Matching IDs can cause WP Users to pick up Guest Author avatars in WP Admin

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/Co-Authors-Plus#907]
When a WP User and Guest Author share the same ID, the WP User can pick up the wrong avatar in the backend.

## Steps to reproduce:

1. Start with a test site that has a Guest Author and WP User that share the same ID. If you don't already have one, the quickest way to recreate is:
    * Set up a new site. 
    * Before adding/importing any posts, install CoAuthors Plus and create a Guest Author. Usually they will have an ID around 5-6. This is necessary because Guest Authors share the same ID pool as other post types.
    * Create 5-6 regular WP Users, until you have one whose ID matches your Guest Author.
2. Give your "ID twin" Guest Author an avatar. 
3. You can also give your "ID twin" WP User an email address that's associated with a Gravatar, but it's not necessary. 
4. View the user list under WP Admin > Users, or view the individual profile of your "ID twin" WP User. Note that the avatar its using is the one assigned to your Guest Author. 

## Screenshots

Guest author settings: 

![image](https://user-images.githubusercontent.com/177561/209243771-3f6c4f97-6021-4977-bd57-4eb70f51a5e0.png)

"ID twin" WP User on the Users screen:

![image](https://user-images.githubusercontent.com/177561/209243830-6b66e896-23b9-461f-b8d3-b475d5f41d9a.png)

Actual avatar the WP User should be using: 

![image](https://user-images.githubusercontent.com/177561/209243863-58d7530c-f199-46a0-bbd0-f98749a72376.png)

**Comment by davidvexel** [comment]
Having this same issue and I think it's because the filter in ```filter_pre_get_avatar_url``` is assuming that the `$id` parameter sent is an Author ID, which is incorrect, I'm seeing the user ID there.

https://github.com/Automattic/Co-Authors-Plus/blob/master/co-authors-plus.php#L1825-L1840

**Comment by GaryJones** [comment]
Fixed in #907.
