### ISSUE TITLE
CAP can break author queries by adding a JOIN and no WHERE

### ISSUE THREAD

**Issue by Viper007Bond** [Automattic/Co-Authors-Plus#91]
A WP.com VIP was doing the following query to fetch posts for a feed:

``` php
$some_query = WP_Query( array(
    'post_status' => 'publish',
    'post_type' => 'post',
    'orderby' => 'modified',
    'order' => 'DESC',
    'posts_per_page' => 20,
    'ignore_sticky_posts' => 1,
    'paged' => 1,
    'post__not_in' => array(),
    'author' => '1,2,3,4,5', // This is the applicable bit to this ticket
    'tag__not_in' => '',
) );
```

`coauthors_plus::posts_join_filter()` would then modify this query and add in some taxonomy `JOIN`s:

``` sql
LEFT JOIN wp_123_term_relationships ON (wp_123_posts.ID = wp_123_term_relationships.object_id) LEFT JOIN wp_123_term_taxonomy ON ( wp_123_term_relationships.term_taxonomy_id = wp_123_term_taxonomy.term_taxonomy_id )
```

However that's it. It doesn't add any `WHERE` arguments and so the resulting query returns duplicate post IDs (the same posts multiple times).

Presumably the duplicates are due to multiple terms being assigned to each post.

**Comment by sanketio** [comment]
@philipjohn

I have tried to replicate this issue, but unable to do so. I can see that posts_where filter is already used for this and it is already adding a condition. So I think this issue is already fixed.

**Comment by philipjohn** [comment]
Brilliant!
