### ISSUE TITLE
Problem with Yoast Slack sharing: List Co Authors Plus authors in the Slack social share

### ISSUE THREAD

**Issue by Hercilio1** [Automattic/Co-Authors-Plus#952]
The Slack social share still gets the native author.

Yoast has a feature that improves social share through Slack. This feature prints the author and the "time to read" of a post. Currently, as I said, it is not getting the Co-Authors Plus authors, but yes the native one.

This feature comes activated by default. You can check it out by going to the general settings of Yoast and looking for the following Social Share resource:
![image](https://github.com/Automattic/Co-Authors-Plus/assets/22755734/627d70d6-d3c0-4dcc-9441-6152f1ea8d02)

After making sure it is activated if you share through Slack a post with a native author that differs from the selected author (selected by Co-Authors block), you will see the native author.

**Comment by Hercilio1** [comment]
You could use the hook `wpseo_enhanced_slack_data` to override the authors meta :smiley:

**Comment by GaryJones** [comment]
@Hercilio1 Would you like to provide a PR for this, please? It seems like you're already familiar with the problem and possible solution.

**Comment by Hercilio1** [comment]
@GaryJones , yes, no problem :)

**Comment by GaryJones** [comment]
Self-note: Enhanced Slack Sharing was added to [Yoast SEO 15.2](https://yoast.com/yoast-seo-15-2/) in October 2020.

**Comment by GaryJones** [comment]
Added with #953.
