### ISSUE TITLE
Increase minimum PHP version

### ISSUE THREAD

**Issue by GaryJones** [Automattic/Co-Authors-Plus#954]
As of right now (3.5.11 has just been released), the minimum PHP version is 5.6.
WordPress 6.3 is about to be released with a minimum PHP version of 7.0.
In a few months, PHP 8.3 will be available.

When 4.0 of CAP is being prepared, then the minimum PHP version can be increased - this helps to reduce bugs (from cross-version differences), reduce testing requirements (not so many combinations to support in CI testing), and can reduce the amount of code to maintain (through more modern syntax).

**Comment by GaryJones** [comment]
The minimum version should be PHP 7.4.

**Comment by alecgeatches** [comment]
Minimum PHP version updated to `7.4` in https://github.com/Automattic/Co-Authors-Plus/pull/1032.
