### ISSUE TITLE
Increase minimum supported WordPress version

### ISSUE THREAD

**Issue by GaryJones** [Automattic/Co-Authors-Plus#955]
As of right now (3.5.11 has just been released) WordPress 6.3 is about to be released. The plugin currently claims to support back to WP 4.1, but realistically the block editor sidebar support only shows up in 5.7 and above.

When 4.0 of CAP is being prepared, then the minimum WP version can be increased - this helps to reduce bugs (from cross-version differences) and reduce testing requirements (not so many combinations to support in CI testing).

With the block editor now far more prevalent, code to support the classic editor can be treated as an integration rather than core/default CAP code.

**Comment by GaryJones** [comment]
Following SemVer, nicely described at https://sebastiandedeyne.com/composer-semver-and-underlying-dependency-changes/ then I'm going to make this happen at a minor bump, which would currently be to 3.6.

**Comment by alecgeatches** [comment]
Minimum WordPress version updated to `5.7` in https://github.com/Automattic/Co-Authors-Plus/pull/1032.
