### ISSUE TITLE
Unable to change avatar image sizes

### ISSUE THREAD

**Issue by douglas-johnson** [Automattic/Co-Authors-Plus#958]
While working on #940 ( specifically while trying to add coauthor avatars to the block editor ), I noticed that `rest_get_avatar_urls()` returned the same URL for all requested sizes.

`rest_get_avatar_urls()` uses `get_avatar_url()` as shown here https://developer.wordpress.org/reference/functions/rest_get_avatar_urls/

- For a user, the requested size is ignored and the default 96px image is always returned.
- For a guest-author with a featured image, the requested size is ignored and the full resolution featured image is always returned.

If I deactivate CoAuthors Plus, obviously there's no guest authors any more, but the user avatars start producing the correct size.

I believe the issues stem from `filter_pre_get_avatar_data_url`

- It calls `get_the_post_thumbnail_url()` and passes a single integer for the size, when an array of integers is expected. So it is treated a request for the full resolution image.
  - https://github.com/Automattic/Co-Authors-Plus/blob/3.5.11/co-authors-plus.php#L1837
- When making its recursive calls to `get_avatar_url()` it does not pass the `$args` which changes the args back to default.
  - https://github.com/Automattic/Co-Authors-Plus/blob/3.5.11/co-authors-plus.php#L1839

Other uses of `get_avatar()` or `get_avatar_url()` in CoAuthors Plus that only return the default size for users, and the full resolution feature image for guest authors:

- https://github.com/Automattic/Co-Authors-Plus/blob/3.5.11/co-authors-plus.php#L452C71-L452C71
- https://github.com/Automattic/Co-Authors-Plus/blob/3.5.11/php/class-coauthors-endpoint.php#L216

**Comment by douglas-johnson** [comment]
this one too: https://github.com/Automattic/Co-Authors-Plus/blob/3.5.11/co-authors-plus.php#L1275

**Comment by douglas-johnson** [comment]
I also noticed this issue #854 which describes avatars incorrectly cropped to the post-thumbnail size and wanted to correct myself because the default size used by `get_the_post_thumbnail_url()` is `post-thumbnail` rather than `full`.

I was testing on the TwentyTewntyThree theme which does not declare a `post-thumbnail` size.

In theory #959 would resolve that issue as well.

**Comment by GaryJones** [comment]
The [gravatar size is set at 25](https://github.com/Automattic/Co-Authors-Plus/blob/179aa52335e5b4448e81dacdb645b11ea5bff485/co-authors-plus.php#L59). Can that be used to control the size for user gravatars and guest author avatars?

**Comment by douglas-johnson** [comment]
@GaryJones It could, but it would override user decisions like selecting the avatar size in the post comment author block. 

From looking at the git history, that size looks like its intended for the CAP admin tools like the coauthors meta box.

It can still be used for that and we can allow other parts of WP to request other sizes.

**Comment by GaryJones** [comment]
@douglas-johnson Understood. In which case, could #958 please include a separate commit that renames the `$gravatar_size` property (and its uses) to something like `$gravatar_size_for_admin` (or better) so that we can properly delineate what it should be used for, and to help clarify what the rest of the PR is, which is allowing other sizes elsewhere?

**Comment by GaryJones** [comment]
> Other uses of get_avatar() or get_avatar_url() in CoAuthors Plus that only return the default size for users, and the full resolution feature image for guest authors

Nice finds - will you be handling this too 🤞🏻, and if so, will that be in #958 or separate PRs?

**Comment by douglas-johnson** [comment]
@GaryJones 

> Nice finds - will you be handling this too 🤞🏻, and if so, will that be in https://github.com/Automattic/Co-Authors-Plus/issues/959 or separate PRs?

Yes, those are addressed by #959.

> Understood. In which case, could https://github.com/Automattic/Co-Authors-Plus/issues/959 please include a separate commit that renames the $gravatar_size property (and its uses) to something like $gravatar_size_for_admin (or better) so that we can properly delineate what it should be used for, and to help clarify what the rest of the PR is, which is allowing other sizes elsewhere?

I could rename it, but may I remove it instead?

After solving this issue, I think the only remaning use of `$gravatar_size` is [here](https://github.com/Automattic/Co-Authors-Plus/blob/3.5.11/co-authors-plus.php#L452) where it is used for a static display of coauthors in the case that an administative user has JavaScript turned off.

I don't think that use case would suffer from using the WordPress default of 96px. That's what the rest of CAP currently uses.

**Comment by GaryJones** [comment]
> I could rename it, but may I remove it instead?
👍🏻  Please do!
