### ISSUE TITLE
Fix PHP Warnings on accessing $coauthor instance

### ISSUE THREAD

**Issue by cobianzo** [Automattic/Co-Authors-Plus#975]
at https://github.com/Automattic/Co-Authors-Plus/blob/master/template-tags.php#L75 we are continously getting PHP warnings for accessnig to inexisting properties `user_login` and `linked_account`.
This could be improved with a simple `isset` verificationi before accessing the values.
```
if ( ( isset( $coauthor->user_login ) && $user == $coauthor->user_login ) || 
		( isset( $coauthor->linked_account ) && $user == $coauthor->linked_account ) ) {
			return true;
		}
```

**Comment by GaryJones** [comment]
Thanks @cobianzo - are you able to determine why `$coauthors` ends up being an array of items that are not the expected objects?

**Comment by cobianzo** [comment]
@GaryJones  Hi I should investigate about it. We have quite a few of customized code which uses $coauthors instances every time we need to access to the author of a post. 
I'll put some time aside to find out in what moment that happens.
