### ISSUE TITLE
Translation strings do not appear on Translating WordPress interface

### ISSUE THREAD

**Issue by antonlukin** [Automattic/Co-Authors-Plus#983]
I want to improve i18n for this plugin, but I can't see strings from the last versions in this interface:
https://translate.wordpress.org/projects/wp-plugins/co-authors-plus/

It seems that the last version of i18n strings is 3.5.11. 
How can we translate new plugin versions?

**Comment by GaryJones** [comment]
https://wordpress.slack.com/archives/C0E7F4RND/p1690842768965349 - since we still claim to support WP 4.1 (I'm not sure we do, but it should only really be bumped on a non-patch), then we still need the text domain header.
